/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module "vue-router" {
    interface TypesConfig {
        ParamParsers: never;
    }
}

declare module "vue-router/auto-routes" {
    /**
     * Route name map generated by vue-router
     */
    export interface RouteNamedMap {
        "/": RouteRecordInfo<"/", "/", Record<never, never>, Record<never, never>, never>;
        "/[...all]": RouteRecordInfo<
            "/[...all]",
            "/:all(.*)",
            { all: ParamValue<true> },
            { all: ParamValue<false> },
            never
        >;
        "/circles/new": RouteRecordInfo<
            "/circles/new",
            "/circles/new",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/circles/select": RouteRecordInfo<
            "/circles/select",
            "/circles/select",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/login": RouteRecordInfo<
            "/login",
            "/login",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/": RouteRecordInfo<
            "/staff/",
            "/staff",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/activity-logs": RouteRecordInfo<
            "/staff/activity-logs",
            "/staff/activity-logs",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/circles/": RouteRecordInfo<
            "/staff/circles/",
            "/staff/circles",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/circles/[circleId]": RouteRecordInfo<
            "/staff/circles/[circleId]",
            "/staff/circles/:circleId",
            { circleId: ParamValue<true> },
            { circleId: ParamValue<false> },
            never
        >;
        "/staff/contact-categories": RouteRecordInfo<
            "/staff/contact-categories",
            "/staff/contact-categories",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/documents/": RouteRecordInfo<
            "/staff/documents/",
            "/staff/documents",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/documents/[documentId]/edit": RouteRecordInfo<
            "/staff/documents/[documentId]/edit",
            "/staff/documents/:documentId/edit",
            { documentId: ParamValue<true> },
            { documentId: ParamValue<false> },
            never
        >;
        "/staff/exports": RouteRecordInfo<
            "/staff/exports",
            "/staff/exports",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/forms/": RouteRecordInfo<
            "/staff/forms/",
            "/staff/forms",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/forms/[formId]/": RouteRecordInfo<
            "/staff/forms/[formId]/",
            "/staff/forms/:formId",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/staff/forms/[formId]/answers/": RouteRecordInfo<
            "/staff/forms/[formId]/answers/",
            "/staff/forms/:formId/answers",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/staff/forms/[formId]/answers/[answerId]/edit": RouteRecordInfo<
            "/staff/forms/[formId]/answers/[answerId]/edit",
            "/staff/forms/:formId/answers/:answerId/edit",
            { formId: ParamValue<true>; answerId: ParamValue<true> },
            { formId: ParamValue<false>; answerId: ParamValue<false> },
            never
        >;
        "/staff/forms/[formId]/answers/create": RouteRecordInfo<
            "/staff/forms/[formId]/answers/create",
            "/staff/forms/:formId/answers/create",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/staff/forms/[formId]/answers/uploads": RouteRecordInfo<
            "/staff/forms/[formId]/answers/uploads",
            "/staff/forms/:formId/answers/uploads",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/staff/forms/[formId]/preview": RouteRecordInfo<
            "/staff/forms/[formId]/preview",
            "/staff/forms/:formId/preview",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/staff/mails": RouteRecordInfo<
            "/staff/mails",
            "/staff/mails",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/pages/": RouteRecordInfo<
            "/staff/pages/",
            "/staff/pages",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/pages/[pageId]": RouteRecordInfo<
            "/staff/pages/[pageId]",
            "/staff/pages/:pageId",
            { pageId: ParamValue<true> },
            { pageId: ParamValue<false> },
            never
        >;
        "/staff/participation-types/": RouteRecordInfo<
            "/staff/participation-types/",
            "/staff/participation-types",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/participation-types/[typeId]": RouteRecordInfo<
            "/staff/participation-types/[typeId]",
            "/staff/participation-types/:typeId",
            { typeId: ParamValue<true> },
            { typeId: ParamValue<false> },
            never
        >;
        "/staff/permissions/": RouteRecordInfo<
            "/staff/permissions/",
            "/staff/permissions",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/permissions/[userId]": RouteRecordInfo<
            "/staff/permissions/[userId]",
            "/staff/permissions/:userId",
            { userId: ParamValue<true> },
            { userId: ParamValue<false> },
            never
        >;
        "/staff/places": RouteRecordInfo<
            "/staff/places",
            "/staff/places",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/settings": RouteRecordInfo<
            "/staff/settings",
            "/staff/settings",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/tags": RouteRecordInfo<
            "/staff/tags",
            "/staff/tags",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/users/": RouteRecordInfo<
            "/staff/users/",
            "/staff/users",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/staff/users/[userId]": RouteRecordInfo<
            "/staff/users/[userId]",
            "/staff/users/:userId",
            { userId: ParamValue<true> },
            { userId: ParamValue<false> },
            never
        >;
        "/staff/verify": RouteRecordInfo<
            "/staff/verify",
            "/staff/verify",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/": RouteRecordInfo<
            "/workspace/",
            "/workspace",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/circles/detail": RouteRecordInfo<
            "/workspace/circles/detail",
            "/workspace/circles/detail",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/circles/members": RouteRecordInfo<
            "/workspace/circles/members",
            "/workspace/circles/members",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/contact": RouteRecordInfo<
            "/workspace/contact",
            "/workspace/contact",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/documents/": RouteRecordInfo<
            "/workspace/documents/",
            "/workspace/documents",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/forms/": RouteRecordInfo<
            "/workspace/forms/",
            "/workspace/forms",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/forms/[formId]": RouteRecordInfo<
            "/workspace/forms/[formId]",
            "/workspace/forms/:formId",
            { formId: ParamValue<true> },
            { formId: ParamValue<false> },
            never
        >;
        "/workspace/pages/": RouteRecordInfo<
            "/workspace/pages/",
            "/workspace/pages",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/workspace/pages/[pageId]": RouteRecordInfo<
            "/workspace/pages/[pageId]",
            "/workspace/pages/:pageId",
            { pageId: ParamValue<true> },
            { pageId: ParamValue<false> },
            never
        >;
        "/workspace/settings": RouteRecordInfo<
            "/workspace/settings",
            "/workspace/settings",
            Record<never, never>,
            Record<never, never>,
            never
        >;
    }

    /**
     * Route file to route info map by vue-router.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * Each key is a file path relative to the project root with 2 properties:
     * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
     * - views: names of nested views (can be passed to <RouterView name="...">)
     *
     * @internal
     */
    export interface _RouteFileInfoMap {
        "src/pages/index.vue": {
            routes: "/";
            views: never;
        };
        "src/pages/[...all].vue": {
            routes: "/[...all]";
            views: never;
        };
        "src/pages/circles/new.vue": {
            routes: "/circles/new";
            views: never;
        };
        "src/pages/circles/select.vue": {
            routes: "/circles/select";
            views: never;
        };
        "src/pages/login.vue": {
            routes: "/login";
            views: never;
        };
        "src/pages/staff/index.vue": {
            routes: "/staff/";
            views: never;
        };
        "src/pages/staff/activity-logs.vue": {
            routes: "/staff/activity-logs";
            views: never;
        };
        "src/pages/staff/circles/index.vue": {
            routes: "/staff/circles/";
            views: never;
        };
        "src/pages/staff/circles/[circleId].vue": {
            routes: "/staff/circles/[circleId]";
            views: never;
        };
        "src/pages/staff/contact-categories.vue": {
            routes: "/staff/contact-categories";
            views: never;
        };
        "src/pages/staff/documents/index.vue": {
            routes: "/staff/documents/";
            views: never;
        };
        "src/pages/staff/documents/[documentId]/edit.vue": {
            routes: "/staff/documents/[documentId]/edit";
            views: never;
        };
        "src/pages/staff/exports.vue": {
            routes: "/staff/exports";
            views: never;
        };
        "src/pages/staff/forms/index.vue": {
            routes: "/staff/forms/";
            views: never;
        };
        "src/pages/staff/forms/[formId]/index.vue": {
            routes: "/staff/forms/[formId]/";
            views: never;
        };
        "src/pages/staff/forms/[formId]/answers/index.vue": {
            routes: "/staff/forms/[formId]/answers/";
            views: never;
        };
        "src/pages/staff/forms/[formId]/answers/[answerId]/edit.vue": {
            routes: "/staff/forms/[formId]/answers/[answerId]/edit";
            views: never;
        };
        "src/pages/staff/forms/[formId]/answers/create.vue": {
            routes: "/staff/forms/[formId]/answers/create";
            views: never;
        };
        "src/pages/staff/forms/[formId]/answers/uploads.vue": {
            routes: "/staff/forms/[formId]/answers/uploads";
            views: never;
        };
        "src/pages/staff/forms/[formId]/preview.vue": {
            routes: "/staff/forms/[formId]/preview";
            views: never;
        };
        "src/pages/staff/mails.vue": {
            routes: "/staff/mails";
            views: never;
        };
        "src/pages/staff/pages/index.vue": {
            routes: "/staff/pages/";
            views: never;
        };
        "src/pages/staff/pages/[pageId].vue": {
            routes: "/staff/pages/[pageId]";
            views: never;
        };
        "src/pages/staff/participation-types/index.vue": {
            routes: "/staff/participation-types/";
            views: never;
        };
        "src/pages/staff/participation-types/[typeId].vue": {
            routes: "/staff/participation-types/[typeId]";
            views: never;
        };
        "src/pages/staff/permissions/index.vue": {
            routes: "/staff/permissions/";
            views: never;
        };
        "src/pages/staff/permissions/[userId].vue": {
            routes: "/staff/permissions/[userId]";
            views: never;
        };
        "src/pages/staff/places.vue": {
            routes: "/staff/places";
            views: never;
        };
        "src/pages/staff/settings.vue": {
            routes: "/staff/settings";
            views: never;
        };
        "src/pages/staff/tags.vue": {
            routes: "/staff/tags";
            views: never;
        };
        "src/pages/staff/users/index.vue": {
            routes: "/staff/users/";
            views: never;
        };
        "src/pages/staff/users/[userId].vue": {
            routes: "/staff/users/[userId]";
            views: never;
        };
        "src/pages/staff/verify.vue": {
            routes: "/staff/verify";
            views: never;
        };
        "src/pages/workspace/index.vue": {
            routes: "/workspace/";
            views: never;
        };
        "src/pages/workspace/circles/detail.vue": {
            routes: "/workspace/circles/detail";
            views: never;
        };
        "src/pages/workspace/circles/members.vue": {
            routes: "/workspace/circles/members";
            views: never;
        };
        "src/pages/workspace/contact.vue": {
            routes: "/workspace/contact";
            views: never;
        };
        "src/pages/workspace/documents/index.vue": {
            routes: "/workspace/documents/";
            views: never;
        };
        "src/pages/workspace/forms/index.vue": {
            routes: "/workspace/forms/";
            views: never;
        };
        "src/pages/workspace/forms/[formId].vue": {
            routes: "/workspace/forms/[formId]";
            views: never;
        };
        "src/pages/workspace/pages/index.vue": {
            routes: "/workspace/pages/";
            views: never;
        };
        "src/pages/workspace/pages/[pageId].vue": {
            routes: "/workspace/pages/[pageId]";
            views: never;
        };
        "src/pages/workspace/settings.vue": {
            routes: "/workspace/settings";
            views: never;
        };
    }

    /**
     * Get a union of possible route names in a certain route component file.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * @internal
     */
    export type _RouteNamesForFilePath<FilePath extends string> =
        _RouteFileInfoMap extends Record<FilePath, infer Info>
            ? Info["routes"]
            : keyof RouteNamedMap;
}

export {};
