import { config, library } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faArrowDown,
  faArrowUp,
  faAt,
  faBell,
  faBold,
  faBullhorn,
  faCheck,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCog,
  faEdit,
  faExclamationCircle,
  faExternalLinkAlt,
  faEye,
  faFileCsv,
  faFileExport,
  faFilter,
  faHeading,
  faHome,
  faInfoCircle,
  faItalic,
  faKey,
  faLink,
  faList,
  faListOl,
  faListUl,
  faLock,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faQuoteRight,
  faSearch,
  faShieldAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faStrikethrough,
  faStore,
  faSync,
  faTable,
  faTags,
  faThumbtack,
  faTimes,
  faTrash,
  faUser,
  faUserEdit
} from '@fortawesome/free-solid-svg-icons'
import {
  faAddressBook,
  faCopy,
  faEdit as faRegularEdit,
  faEnvelope,
  faEye as faRegularEye,
  faFileAlt,
  faFileArchive
} from '@fortawesome/free-regular-svg-icons'

let isInitialized = false

export function initializeFontAwesome() {
  if (isInitialized) {
    return
  }

  config.autoAddCss = false

  library.add(
    faAddressBook,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faArrowDown,
    faArrowUp,
    faAt,
    faBell,
    faBold,
    faBullhorn,
    faCheck,
    faCheckCircle,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faCog,
    faCopy,
    faEdit,
    faEnvelope,
    faExclamationCircle,
    faExternalLinkAlt,
    faEye,
    faFileAlt,
    faRegularEye,
    faFileArchive,
    faFileCsv,
    faFileExport,
    faFilter,
    faHeading,
    faHome,
    faInfoCircle,
    faItalic,
    faKey,
    faLink,
    faList,
    faListOl,
    faListUl,
    faLock,
    faPencilAlt,
    faPlus,
    faQuestionCircle,
    faQuoteRight,
    faRegularEdit,
    faSearch,
    faShieldAlt,
    faSort,
    faSortDown,
    faSortUp,
    faSpinner,
    faStar,
    faStrikethrough,
    faStore,
    faSync,
    faTable,
    faTags,
    faThumbtack,
    faTimes,
    faTrash,
    faUser,
    faUserEdit
  )

  isInitialized = true
}
