import type { IconDefinition, IconPrefix } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faArrowDown,
  faArrowUp,
  faAt,
  faBell,
  faBold,
  faBullhorn,
  faCheck,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCog,
  faEdit,
  faExclamationCircle,
  faExternalLinkAlt,
  faEye,
  faFileCsv,
  faFileExport,
  faFilter,
  faHeading,
  faHome,
  faInfoCircle,
  faItalic,
  faKey,
  faLink,
  faList,
  faListOl,
  faListUl,
  faLock,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faQuoteRight,
  faSearch,
  faShieldAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faStrikethrough,
  faStore,
  faSync,
  faTable,
  faTags,
  faThumbtack,
  faTimes,
  faTrash,
  faUser,
  faUserEdit
} from '@fortawesome/free-solid-svg-icons'
import {
  faAddressBook,
  faCopy,
  faEdit as faRegularEdit,
  faEnvelope,
  faEye as faRegularEye,
  faFileAlt,
  faFileArchive
} from '@fortawesome/free-regular-svg-icons'

export const iconDefinitions: readonly IconDefinition[] = [
  faAddressBook,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faArrowDown,
  faArrowUp,
  faAt,
  faBell,
  faBold,
  faBullhorn,
  faCheck,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faCog,
  faCopy,
  faEdit,
  faEnvelope,
  faExclamationCircle,
  faExternalLinkAlt,
  faEye,
  faFileAlt,
  faRegularEye,
  faFileArchive,
  faFileCsv,
  faFileExport,
  faFilter,
  faHeading,
  faHome,
  faInfoCircle,
  faItalic,
  faKey,
  faLink,
  faList,
  faListOl,
  faListUl,
  faLock,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faQuoteRight,
  faRegularEdit,
  faSearch,
  faShieldAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faStrikethrough,
  faStore,
  faSync,
  faTable,
  faTags,
  faThumbtack,
  faTimes,
  faTrash,
  faUser,
  faUserEdit
]

const definitionsByName = new Map<string, IconDefinition>()

for (const definition of iconDefinitions) {
  definitionsByName.set(`${definition.prefix}:${definition.iconName}`, definition)
  for (const alias of definition.icon[2]) {
    definitionsByName.set(`${definition.prefix}:${alias}`, definition)
  }
}

export function findIconDefinition(prefix: IconPrefix, iconName: string): IconDefinition | undefined {
  return definitionsByName.get(`${prefix}:${iconName}`)
}
