// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package db

import (
	"context"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    actor_user_id,
    action,
    target_type,
    target_id,
    circle_id,
    summary
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, actor_user_id, action, target_type, target_id, circle_id, summary, created_at
`

type CreateActivityLogParams struct {
	ActorUserID string
	Action      string
	TargetType  string
	TargetID    string
	CircleID    string
	Summary     string
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.CircleID,
		arg.Summary,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.CircleID,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, actor_user_id, action, target_type, target_id, circle_id, summary, created_at
FROM activity_logs
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListActivityLogs(ctx context.Context) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.CircleID,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
