// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (form_id, circle_id, body)
VALUES ($1, $2, $3)
RETURNING id, form_id, circle_id, body, updated_at, created_at
`

type CreateAnswerParams struct {
	FormID   string
	CircleID string
	Body     string
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer, arg.FormID, arg.CircleID, arg.Body)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CircleID,
		&i.Body,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAnswerDetail = `-- name: CreateAnswerDetail :one
INSERT INTO answer_details (answer_id, form_id, circle_id, question_id, value, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, answer_id, form_id, circle_id, question_id, value, position, created_at
`

type CreateAnswerDetailParams struct {
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID string
	Value      string
	Position   int32
}

func (q *Queries) CreateAnswerDetail(ctx context.Context, arg CreateAnswerDetailParams) (AnswerDetail, error) {
	row := q.db.QueryRow(ctx, createAnswerDetail,
		arg.AnswerID,
		arg.FormID,
		arg.CircleID,
		arg.QuestionID,
		arg.Value,
		arg.Position,
	)
	var i AnswerDetail
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.FormID,
		&i.CircleID,
		&i.QuestionID,
		&i.Value,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createAnswerUpload = `-- name: CreateAnswerUpload :one
INSERT INTO answer_uploads (answer_id, form_id, circle_id, question_id, filename, mime_type, content, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, answer_id, form_id, circle_id, question_id, filename, mime_type, size_bytes, created_at
`

type CreateAnswerUploadParams struct {
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID pgtype.Text
	Filename   string
	MimeType   string
	Content    []byte
	SizeBytes  int64
}

type CreateAnswerUploadRow struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID pgtype.Text
	Filename   string
	MimeType   string
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAnswerUpload(ctx context.Context, arg CreateAnswerUploadParams) (CreateAnswerUploadRow, error) {
	row := q.db.QueryRow(ctx, createAnswerUpload,
		arg.AnswerID,
		arg.FormID,
		arg.CircleID,
		arg.QuestionID,
		arg.Filename,
		arg.MimeType,
		arg.Content,
		arg.SizeBytes,
	)
	var i CreateAnswerUploadRow
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.FormID,
		&i.CircleID,
		&i.QuestionID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnswerByID = `-- name: DeleteAnswerByID :execrows
DELETE FROM answers
WHERE id = $1
`

func (q *Queries) DeleteAnswerByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnswerByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAnswerDetailsByAnswer = `-- name: DeleteAnswerDetailsByAnswer :execrows
DELETE FROM answer_details
WHERE answer_id = $1
`

func (q *Queries) DeleteAnswerDetailsByAnswer(ctx context.Context, answerID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnswerDetailsByAnswer, answerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAnswerUploadsByAnswerAndQuestion = `-- name: DeleteAnswerUploadsByAnswerAndQuestion :execrows
DELETE FROM answer_uploads
WHERE answer_id = $1
  AND question_id = $2
`

type DeleteAnswerUploadsByAnswerAndQuestionParams struct {
	AnswerID   string
	QuestionID pgtype.Text
}

func (q *Queries) DeleteAnswerUploadsByAnswerAndQuestion(ctx context.Context, arg DeleteAnswerUploadsByAnswerAndQuestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnswerUploadsByAnswerAndQuestion, arg.AnswerID, arg.QuestionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT id, form_id, circle_id, body, updated_at, created_at
FROM answers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAnswerByID(ctx context.Context, id string) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByID, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CircleID,
		&i.Body,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerUploadFileByAnswerAndQuestion = `-- name: GetAnswerUploadFileByAnswerAndQuestion :one
SELECT id, answer_id, form_id, circle_id, question_id, filename, mime_type, content, size_bytes, created_at
FROM answer_uploads
WHERE answer_id = $1
  AND question_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetAnswerUploadFileByAnswerAndQuestionParams struct {
	AnswerID   string
	QuestionID pgtype.Text
}

type GetAnswerUploadFileByAnswerAndQuestionRow struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID pgtype.Text
	Filename   string
	MimeType   string
	Content    []byte
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetAnswerUploadFileByAnswerAndQuestion(ctx context.Context, arg GetAnswerUploadFileByAnswerAndQuestionParams) (GetAnswerUploadFileByAnswerAndQuestionRow, error) {
	row := q.db.QueryRow(ctx, getAnswerUploadFileByAnswerAndQuestion, arg.AnswerID, arg.QuestionID)
	var i GetAnswerUploadFileByAnswerAndQuestionRow
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.FormID,
		&i.CircleID,
		&i.QuestionID,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerUploadFileByID = `-- name: GetAnswerUploadFileByID :one
SELECT id, answer_id, form_id, circle_id, question_id, filename, mime_type, content, size_bytes, created_at
FROM answer_uploads
WHERE id = $1
LIMIT 1
`

type GetAnswerUploadFileByIDRow struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID pgtype.Text
	Filename   string
	MimeType   string
	Content    []byte
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetAnswerUploadFileByID(ctx context.Context, id string) (GetAnswerUploadFileByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnswerUploadFileByID, id)
	var i GetAnswerUploadFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.AnswerID,
		&i.FormID,
		&i.CircleID,
		&i.QuestionID,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAnswerByFormAndCircle = `-- name: GetLatestAnswerByFormAndCircle :one
SELECT id, form_id, circle_id, body, updated_at, created_at
FROM answers
WHERE form_id = $1
  AND circle_id = $2
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetLatestAnswerByFormAndCircleParams struct {
	FormID   string
	CircleID string
}

func (q *Queries) GetLatestAnswerByFormAndCircle(ctx context.Context, arg GetLatestAnswerByFormAndCircleParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getLatestAnswerByFormAndCircle, arg.FormID, arg.CircleID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CircleID,
		&i.Body,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAnswerDetailsByAnswerID = `-- name: ListAnswerDetailsByAnswerID :many
SELECT id, answer_id, form_id, circle_id, question_id, value, position, created_at
FROM answer_details
WHERE answer_id = $1
ORDER BY question_id ASC, position ASC, created_at ASC
`

func (q *Queries) ListAnswerDetailsByAnswerID(ctx context.Context, answerID string) ([]AnswerDetail, error) {
	rows, err := q.db.Query(ctx, listAnswerDetailsByAnswerID, answerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnswerDetail
	for rows.Next() {
		var i AnswerDetail
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.FormID,
			&i.CircleID,
			&i.QuestionID,
			&i.Value,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswerUploadsByAnswerID = `-- name: ListAnswerUploadsByAnswerID :many
SELECT id, answer_id, form_id, circle_id, question_id, filename, mime_type, size_bytes, created_at
FROM answer_uploads
WHERE answer_id = $1
ORDER BY created_at DESC, id DESC
`

type ListAnswerUploadsByAnswerIDRow struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID pgtype.Text
	Filename   string
	MimeType   string
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAnswerUploadsByAnswerID(ctx context.Context, answerID string) ([]ListAnswerUploadsByAnswerIDRow, error) {
	rows, err := q.db.Query(ctx, listAnswerUploadsByAnswerID, answerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswerUploadsByAnswerIDRow
	for rows.Next() {
		var i ListAnswerUploadsByAnswerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AnswerID,
			&i.FormID,
			&i.CircleID,
			&i.QuestionID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByCircle = `-- name: ListAnswersByCircle :many
SELECT id, form_id, circle_id, body, updated_at, created_at
FROM answers
WHERE circle_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListAnswersByCircle(ctx context.Context, circleID string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.CircleID,
			&i.Body,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByForm = `-- name: ListAnswersByForm :many
SELECT id, form_id, circle_id, body, updated_at, created_at
FROM answers
WHERE form_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListAnswersByForm(ctx context.Context, formID string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByForm, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.CircleID,
			&i.Body,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByFormAndCircle = `-- name: ListAnswersByFormAndCircle :many
SELECT id, form_id, circle_id, body, updated_at, created_at
FROM answers
WHERE form_id = $1
  AND circle_id = $2
ORDER BY updated_at DESC, id DESC
`

type ListAnswersByFormAndCircleParams struct {
	FormID   string
	CircleID string
}

func (q *Queries) ListAnswersByFormAndCircle(ctx context.Context, arg ListAnswersByFormAndCircleParams) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByFormAndCircle, arg.FormID, arg.CircleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.CircleID,
			&i.Body,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswerByID = `-- name: UpdateAnswerByID :one
UPDATE answers
SET body = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, form_id, circle_id, body, updated_at, created_at
`

type UpdateAnswerByIDParams struct {
	ID   string
	Body string
}

func (q *Queries) UpdateAnswerByID(ctx context.Context, arg UpdateAnswerByIDParams) (Answer, error) {
	row := q.db.QueryRow(ctx, updateAnswerByID, arg.ID, arg.Body)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.CircleID,
		&i.Body,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
