// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booths.sql

package db

import (
	"context"
)

const deleteBoothsByCircle = `-- name: DeleteBoothsByCircle :exec
DELETE FROM booths
WHERE circle_id = $1
`

func (q *Queries) DeleteBoothsByCircle(ctx context.Context, circleID string) error {
	_, err := q.db.Exec(ctx, deleteBoothsByCircle, circleID)
	return err
}

const deleteBoothsByPlace = `-- name: DeleteBoothsByPlace :exec
DELETE FROM booths
WHERE place_id = $1
`

func (q *Queries) DeleteBoothsByPlace(ctx context.Context, placeID string) error {
	_, err := q.db.Exec(ctx, deleteBoothsByPlace, placeID)
	return err
}

const listBooths = `-- name: ListBooths :many
SELECT place_id, circle_id
FROM booths
ORDER BY place_id ASC, circle_id ASC
`

type ListBoothsRow struct {
	PlaceID  string
	CircleID string
}

func (q *Queries) ListBooths(ctx context.Context) ([]ListBoothsRow, error) {
	rows, err := q.db.Query(ctx, listBooths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoothsRow
	for rows.Next() {
		var i ListBoothsRow
		if err := rows.Scan(&i.PlaceID, &i.CircleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
