// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: circles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCircle = `-- name: CreateCircle :one
INSERT INTO circles (
    id,
    name,
    group_name,
    participation_type_id,
    participation_type_name,
    tags
) VALUES (
    gen_random_uuid()::text,
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, group_name, participation_type_id, participation_type_name, tags, created_at
`

type CreateCircleParams struct {
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
}

type CreateCircleRow struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (CreateCircleRow, error) {
	row := q.db.QueryRow(ctx, createCircle,
		arg.Name,
		arg.GroupName,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	var i CreateCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupName,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCircle = `-- name: DeleteCircle :exec
DELETE FROM circles
WHERE id = $1
`

func (q *Queries) DeleteCircle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCircle, id)
	return err
}

const getCircleByID = `-- name: GetCircleByID :one
SELECT id, name, group_name, participation_type_id, participation_type_name, tags, created_at
FROM circles
WHERE id = $1
`

type GetCircleByIDRow struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetCircleByID(ctx context.Context, id string) (GetCircleByIDRow, error) {
	row := q.db.QueryRow(ctx, getCircleByID, id)
	var i GetCircleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupName,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listCircles = `-- name: ListCircles :many
SELECT id, name, group_name, participation_type_id, participation_type_name, tags, created_at
FROM circles
ORDER BY id
`

type ListCirclesRow struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListCircles(ctx context.Context) ([]ListCirclesRow, error) {
	rows, err := q.db.Query(ctx, listCircles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCirclesRow
	for rows.Next() {
		var i ListCirclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupName,
			&i.ParticipationTypeID,
			&i.ParticipationTypeName,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCircle = `-- name: UpdateCircle :one
UPDATE circles
SET name = $2,
    group_name = $3,
    participation_type_id = $4,
    participation_type_name = $5,
    tags = $6
WHERE id = $1
RETURNING id, name, group_name, participation_type_id, participation_type_name, tags, created_at
`

type UpdateCircleParams struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
}

type UpdateCircleRow struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateCircle(ctx context.Context, arg UpdateCircleParams) (UpdateCircleRow, error) {
	row := q.db.QueryRow(ctx, updateCircle,
		arg.ID,
		arg.Name,
		arg.GroupName,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	var i UpdateCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupName,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}
