// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: circles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCircleMembers = `-- name: CountCircleMembers :one
SELECT COUNT(*) FROM circle_user WHERE circle_id = $1
`

func (q *Queries) CountCircleMembers(ctx context.Context, circleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCircleMembers, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCircle = `-- name: CreateCircle :one
INSERT INTO circles (
    id,
    name,
    group_name,
    participation_type_id,
    participation_type_name,
    tags
) VALUES (
    uuidv7(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type CreateCircleParams struct {
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
}

type CreateCircleRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (CreateCircleRow, error) {
	row := q.db.QueryRow(ctx, createCircle,
		arg.Name,
		arg.GroupName,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	var i CreateCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const createCircleUser = `-- name: CreateCircleUser :exec
INSERT INTO circle_user (circle_id, user_id, is_leader)
VALUES ($1, $2, $3)
`

type CreateCircleUserParams struct {
	CircleID string
	UserID   string
	IsLeader bool
}

func (q *Queries) CreateCircleUser(ctx context.Context, arg CreateCircleUserParams) error {
	_, err := q.db.Exec(ctx, createCircleUser, arg.CircleID, arg.UserID, arg.IsLeader)
	return err
}

const createUserCircle = `-- name: CreateUserCircle :one
INSERT INTO circles (
    id,
    name,
    name_yomi,
    group_name,
    group_name_yomi,
    participation_type_id,
    participation_type_name,
    notes,
    can_change_group_name,
    invitation_token
) VALUES (
    uuidv7(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    encode(gen_random_bytes(16), 'hex')
)
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type CreateUserCircleParams struct {
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Notes                 string
	CanChangeGroupName    bool
}

type CreateUserCircleRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateUserCircle(ctx context.Context, arg CreateUserCircleParams) (CreateUserCircleRow, error) {
	row := q.db.QueryRow(ctx, createUserCircle,
		arg.Name,
		arg.NameYomi,
		arg.GroupName,
		arg.GroupNameYomi,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Notes,
		arg.CanChangeGroupName,
	)
	var i CreateUserCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCircle = `-- name: DeleteCircle :exec
DELETE FROM circles
WHERE id = $1
`

func (q *Queries) DeleteCircle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCircle, id)
	return err
}

const getCircleByID = `-- name: GetCircleByID :one
SELECT id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
FROM circles
WHERE id = $1
`

type GetCircleByIDRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetCircleByID(ctx context.Context, id string) (GetCircleByIDRow, error) {
	row := q.db.QueryRow(ctx, getCircleByID, id)
	var i GetCircleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCircleByInvitationToken = `-- name: GetCircleByInvitationToken :one
SELECT id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
FROM circles
WHERE invitation_token = $1
`

type GetCircleByInvitationTokenRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetCircleByInvitationToken(ctx context.Context, invitationToken pgtype.Text) (GetCircleByInvitationTokenRow, error) {
	row := q.db.QueryRow(ctx, getCircleByInvitationToken, invitationToken)
	var i GetCircleByInvitationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCircle = `-- name: GetUserCircle :one
SELECT c.id, c.name, c.name_yomi, c.group_name, c.group_name_yomi, c.participation_type_id, c.participation_type_name, c.tags, c.invitation_token, c.submitted_at, c.notes, c.can_change_group_name, c.updated_at, c.status, c.status_reason, c.status_set_at, c.status_set_by, c.created_at
FROM circles c
JOIN circle_user cu ON cu.circle_id = c.id
WHERE c.id = $1 AND cu.user_id = $2
`

type GetUserCircleParams struct {
	ID     string
	UserID string
}

type GetUserCircleRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetUserCircle(ctx context.Context, arg GetUserCircleParams) (GetUserCircleRow, error) {
	row := q.db.QueryRow(ctx, getUserCircle, arg.ID, arg.UserID)
	var i GetUserCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const isCircleLeader = `-- name: IsCircleLeader :one
SELECT EXISTS(SELECT 1 FROM circle_user WHERE circle_id = $1 AND user_id = $2 AND is_leader = true) AS exists
`

type IsCircleLeaderParams struct {
	CircleID string
	UserID   string
}

func (q *Queries) IsCircleLeader(ctx context.Context, arg IsCircleLeaderParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCircleLeader, arg.CircleID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isCircleMember = `-- name: IsCircleMember :one
SELECT EXISTS(SELECT 1 FROM circle_user WHERE circle_id = $1 AND user_id = $2) AS exists
`

type IsCircleMemberParams struct {
	CircleID string
	UserID   string
}

func (q *Queries) IsCircleMember(ctx context.Context, arg IsCircleMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCircleMember, arg.CircleID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCircleMembers = `-- name: ListCircleMembers :many
SELECT u.id, u.display_name, cu.is_leader
FROM circle_user cu
JOIN users u ON u.id = cu.user_id
WHERE cu.circle_id = $1
ORDER BY cu.is_leader DESC, u.display_name
`

type ListCircleMembersRow struct {
	ID          string
	DisplayName string
	IsLeader    bool
}

func (q *Queries) ListCircleMembers(ctx context.Context, circleID string) ([]ListCircleMembersRow, error) {
	rows, err := q.db.Query(ctx, listCircleMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCircleMembersRow
	for rows.Next() {
		var i ListCircleMembersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.IsLeader); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCirclePlaceNames = `-- name: ListCirclePlaceNames :many
SELECT b.circle_id, p.name
FROM booths b
JOIN places p ON p.id = b.place_id
WHERE b.circle_id = ANY($1::uuid[])
ORDER BY b.circle_id, p.name
`

type ListCirclePlaceNamesRow struct {
	CircleID string
	Name     string
}

func (q *Queries) ListCirclePlaceNames(ctx context.Context, dollar_1 []string) ([]ListCirclePlaceNamesRow, error) {
	rows, err := q.db.Query(ctx, listCirclePlaceNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCirclePlaceNamesRow
	for rows.Next() {
		var i ListCirclePlaceNamesRow
		if err := rows.Scan(&i.CircleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCircles = `-- name: ListCircles :many
SELECT id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
FROM circles
ORDER BY id
`

type ListCirclesRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListCircles(ctx context.Context) ([]ListCirclesRow, error) {
	rows, err := q.db.Query(ctx, listCircles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCirclesRow
	for rows.Next() {
		var i ListCirclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameYomi,
			&i.GroupName,
			&i.GroupNameYomi,
			&i.ParticipationTypeID,
			&i.ParticipationTypeName,
			&i.Tags,
			&i.InvitationToken,
			&i.SubmittedAt,
			&i.Notes,
			&i.CanChangeGroupName,
			&i.UpdatedAt,
			&i.Status,
			&i.StatusReason,
			&i.StatusSetAt,
			&i.StatusSetBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCircles = `-- name: ListUserCircles :many
SELECT c.id, c.name, c.name_yomi, c.group_name, c.group_name_yomi, c.participation_type_id, c.participation_type_name, c.tags, c.invitation_token, c.submitted_at, c.notes, c.can_change_group_name, c.updated_at, c.status, c.status_reason, c.status_set_at, c.status_set_by, c.created_at
FROM circles c
JOIN circle_user cu ON cu.circle_id = c.id
WHERE cu.user_id = $1
ORDER BY c.id
`

type ListUserCirclesRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) ListUserCircles(ctx context.Context, userID string) ([]ListUserCirclesRow, error) {
	rows, err := q.db.Query(ctx, listUserCircles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCirclesRow
	for rows.Next() {
		var i ListUserCirclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameYomi,
			&i.GroupName,
			&i.GroupNameYomi,
			&i.ParticipationTypeID,
			&i.ParticipationTypeName,
			&i.Tags,
			&i.InvitationToken,
			&i.SubmittedAt,
			&i.Notes,
			&i.CanChangeGroupName,
			&i.UpdatedAt,
			&i.Status,
			&i.StatusReason,
			&i.StatusSetAt,
			&i.StatusSetBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCircleMember = `-- name: RemoveCircleMember :exec
DELETE FROM circle_user
WHERE circle_id = $1 AND user_id = $2
`

type RemoveCircleMemberParams struct {
	CircleID string
	UserID   string
}

func (q *Queries) RemoveCircleMember(ctx context.Context, arg RemoveCircleMemberParams) error {
	_, err := q.db.Exec(ctx, removeCircleMember, arg.CircleID, arg.UserID)
	return err
}

const setCircleStatus = `-- name: SetCircleStatus :one
UPDATE circles
SET status = $2,
    status_reason = $3,
    status_set_at = CASE WHEN $2 = 'approved' OR $2 = 'rejected' THEN now() ELSE NULL END,
    status_set_by = CASE WHEN ($2 = 'approved' OR $2 = 'rejected') AND $4::text != '' THEN $4 ELSE NULL END
WHERE id = $1
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type SetCircleStatusParams struct {
	ID           string
	Status       string
	StatusReason string
	Column4      string
}

type SetCircleStatusRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) SetCircleStatus(ctx context.Context, arg SetCircleStatusParams) (SetCircleStatusRow, error) {
	row := q.db.QueryRow(ctx, setCircleStatus,
		arg.ID,
		arg.Status,
		arg.StatusReason,
		arg.Column4,
	)
	var i SetCircleStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const submitCircle = `-- name: SubmitCircle :one
UPDATE circles
SET submitted_at = now()
WHERE id = $1
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type SubmitCircleRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) SubmitCircle(ctx context.Context, id string) (SubmitCircleRow, error) {
	row := q.db.QueryRow(ctx, submitCircle, id)
	var i SubmitCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCircle = `-- name: UpdateCircle :one
UPDATE circles
SET name = $2,
    group_name = $3,
    participation_type_id = $4,
    participation_type_name = $5,
    tags = $6
WHERE id = $1
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type UpdateCircleParams struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
}

type UpdateCircleRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateCircle(ctx context.Context, arg UpdateCircleParams) (UpdateCircleRow, error) {
	row := q.db.QueryRow(ctx, updateCircle,
		arg.ID,
		arg.Name,
		arg.GroupName,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	var i UpdateCircleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCircleDetails = `-- name: UpdateCircleDetails :one
UPDATE circles
SET name = $2,
    name_yomi = $3,
    group_name = $4,
    group_name_yomi = $5,
    notes = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type UpdateCircleDetailsParams struct {
	ID            string
	Name          string
	NameYomi      string
	GroupName     string
	GroupNameYomi string
	Notes         string
}

type UpdateCircleDetailsRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateCircleDetails(ctx context.Context, arg UpdateCircleDetailsParams) (UpdateCircleDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateCircleDetails,
		arg.ID,
		arg.Name,
		arg.NameYomi,
		arg.GroupName,
		arg.GroupNameYomi,
		arg.Notes,
	)
	var i UpdateCircleDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCircleInvitationToken = `-- name: UpdateCircleInvitationToken :one
UPDATE circles
SET invitation_token = encode(gen_random_bytes(16), 'hex')
WHERE id = $1
RETURNING id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags, invitation_token, submitted_at, notes, can_change_group_name, updated_at, status, status_reason, status_set_at, status_set_by, created_at
`

type UpdateCircleInvitationTokenRow struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateCircleInvitationToken(ctx context.Context, id string) (UpdateCircleInvitationTokenRow, error) {
	row := q.db.QueryRow(ctx, updateCircleInvitationToken, id)
	var i UpdateCircleInvitationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameYomi,
		&i.GroupName,
		&i.GroupNameYomi,
		&i.ParticipationTypeID,
		&i.ParticipationTypeName,
		&i.Tags,
		&i.InvitationToken,
		&i.SubmittedAt,
		&i.Notes,
		&i.CanChangeGroupName,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusReason,
		&i.StatusSetAt,
		&i.StatusSetBy,
		&i.CreatedAt,
	)
	return i, err
}
