// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_categories.sql

package db

import (
	"context"
)

const createContactCategory = `-- name: CreateContactCategory :one
INSERT INTO contact_categories (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at, updated_at
`

type CreateContactCategoryParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateContactCategory(ctx context.Context, arg CreateContactCategoryParams) (ContactCategory, error) {
	row := q.db.QueryRow(ctx, createContactCategory, arg.Name, arg.Email)
	var i ContactCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContactCategory = `-- name: DeleteContactCategory :execrows
DELETE FROM contact_categories
WHERE id = $1
`

func (q *Queries) DeleteContactCategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listContactCategories = `-- name: ListContactCategories :many
SELECT id, name, email, created_at, updated_at
FROM contact_categories
ORDER BY name ASC
`

func (q *Queries) ListContactCategories(ctx context.Context) ([]ContactCategory, error) {
	rows, err := q.db.Query(ctx, listContactCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactCategory
	for rows.Next() {
		var i ContactCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactCategory = `-- name: UpdateContactCategory :one
UPDATE contact_categories
SET name = $2,
    email = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, email, created_at, updated_at
`

type UpdateContactCategoryParams struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) UpdateContactCategory(ctx context.Context, arg UpdateContactCategoryParams) (ContactCategory, error) {
	row := q.db.QueryRow(ctx, updateContactCategory, arg.ID, arg.Name, arg.Email)
	var i ContactCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
