// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffDocument = `-- name: CreateStaffDocument :one
INSERT INTO documents (circle_id, name, description, notes, is_public, is_important, filename, mime_type, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
`

type CreateStaffDocumentParams struct {
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
}

type CreateStaffDocumentRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateStaffDocument(ctx context.Context, arg CreateStaffDocumentParams) (CreateStaffDocumentRow, error) {
	row := q.db.QueryRow(ctx, createStaffDocument,
		arg.CircleID,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.IsPublic,
		arg.IsImportant,
		arg.Filename,
		arg.MimeType,
		arg.Content,
	)
	var i CreateStaffDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffDocument = `-- name: DeleteStaffDocument :execrows
DELETE FROM documents
WHERE circle_id = $1
  AND id = $2
`

type DeleteStaffDocumentParams struct {
	CircleID string
	ID       string
}

func (q *Queries) DeleteStaffDocument(ctx context.Context, arg DeleteStaffDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaffDocument, arg.CircleID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublicDocumentByID = `-- name: GetPublicDocumentByID :one
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE circle_id = $1
  AND id = $2
  AND is_public = true
LIMIT 1
`

type GetPublicDocumentByIDParams struct {
	CircleID string
	ID       string
}

type GetPublicDocumentByIDRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPublicDocumentByID(ctx context.Context, arg GetPublicDocumentByIDParams) (GetPublicDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicDocumentByID, arg.CircleID, arg.ID)
	var i GetPublicDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicDocumentByIDGlobal = `-- name: GetPublicDocumentByIDGlobal :one
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE id = $1
  AND is_public = true
LIMIT 1
`

type GetPublicDocumentByIDGlobalRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPublicDocumentByIDGlobal(ctx context.Context, id string) (GetPublicDocumentByIDGlobalRow, error) {
	row := q.db.QueryRow(ctx, getPublicDocumentByIDGlobal, id)
	var i GetPublicDocumentByIDGlobalRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffDocumentByID = `-- name: GetStaffDocumentByID :one
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE circle_id = $1
  AND id = $2
LIMIT 1
`

type GetStaffDocumentByIDParams struct {
	CircleID string
	ID       string
}

type GetStaffDocumentByIDRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetStaffDocumentByID(ctx context.Context, arg GetStaffDocumentByIDParams) (GetStaffDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStaffDocumentByID, arg.CircleID, arg.ID)
	var i GetStaffDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffDocumentByIDGlobal = `-- name: GetStaffDocumentByIDGlobal :one
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE id = $1
LIMIT 1
`

type GetStaffDocumentByIDGlobalRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetStaffDocumentByIDGlobal(ctx context.Context, id string) (GetStaffDocumentByIDGlobalRow, error) {
	row := q.db.QueryRow(ctx, getStaffDocumentByIDGlobal, id)
	var i GetStaffDocumentByIDGlobalRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicDocuments = `-- name: ListPublicDocuments :many
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE is_public = true
ORDER BY updated_at DESC, id DESC
`

type ListPublicDocumentsRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPublicDocuments(ctx context.Context) ([]ListPublicDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicDocumentsRow
	for rows.Next() {
		var i ListPublicDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.IsPublic,
			&i.IsImportant,
			&i.Filename,
			&i.MimeType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDocumentsByCircle = `-- name: ListPublicDocumentsByCircle :many
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE circle_id = $1
  AND is_public = true
ORDER BY updated_at DESC, id DESC
`

type ListPublicDocumentsByCircleRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPublicDocumentsByCircle(ctx context.Context, circleID string) ([]ListPublicDocumentsByCircleRow, error) {
	rows, err := q.db.Query(ctx, listPublicDocumentsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicDocumentsByCircleRow
	for rows.Next() {
		var i ListPublicDocumentsByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.IsPublic,
			&i.IsImportant,
			&i.Filename,
			&i.MimeType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadDocumentIDsByUser = `-- name: ListReadDocumentIDsByUser :many
SELECT document_id
FROM document_reads
WHERE user_id = $1
  AND document_id = ANY($2::uuid[])
`

type ListReadDocumentIDsByUserParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListReadDocumentIDsByUser(ctx context.Context, arg ListReadDocumentIDsByUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReadDocumentIDsByUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffDocumentsByCircle = `-- name: ListStaffDocumentsByCircle :many
SELECT id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE circle_id = $1
ORDER BY updated_at DESC, id DESC
`

type ListStaffDocumentsByCircleRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListStaffDocumentsByCircle(ctx context.Context, circleID string) ([]ListStaffDocumentsByCircleRow, error) {
	rows, err := q.db.Query(ctx, listStaffDocumentsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffDocumentsByCircleRow
	for rows.Next() {
		var i ListStaffDocumentsByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.IsPublic,
			&i.IsImportant,
			&i.Filename,
			&i.MimeType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentRead = `-- name: MarkDocumentRead :exec
INSERT INTO document_reads (document_id, user_id)
VALUES ($1, $2)
ON CONFLICT (document_id, user_id) DO NOTHING
`

type MarkDocumentReadParams struct {
	DocumentID string
	UserID     string
}

func (q *Queries) MarkDocumentRead(ctx context.Context, arg MarkDocumentReadParams) error {
	_, err := q.db.Exec(ctx, markDocumentRead, arg.DocumentID, arg.UserID)
	return err
}

const updateStaffDocument = `-- name: UpdateStaffDocument :one
UPDATE documents
SET name = $3,
    description = $4,
    notes = $5,
    is_public = $6,
    is_important = $7,
    filename = $8,
    mime_type = $9,
    content = $10,
    updated_at = now()
WHERE circle_id = $1
  AND id = $2
RETURNING id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at
`

type UpdateStaffDocumentParams struct {
	CircleID    string
	ID          string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
}

type UpdateStaffDocumentRow struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateStaffDocument(ctx context.Context, arg UpdateStaffDocumentParams) (UpdateStaffDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateStaffDocument,
		arg.CircleID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.IsPublic,
		arg.IsImportant,
		arg.Filename,
		arg.MimeType,
		arg.Content,
	)
	var i UpdateStaffDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
