// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffDocument = `-- name: CreateStaffDocument :one
INSERT INTO documents (name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
`

type CreateStaffDocumentParams struct {
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
}

type CreateStaffDocumentRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateStaffDocument(ctx context.Context, arg CreateStaffDocumentParams) (CreateStaffDocumentRow, error) {
	row := q.db.QueryRow(ctx, createStaffDocument,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.IsPublic,
		arg.ViewableTags,
		arg.IsImportant,
		arg.Filename,
		arg.MimeType,
		arg.Content,
	)
	var i CreateStaffDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.ViewableTags,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffDocument = `-- name: DeleteStaffDocument :execrows
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteStaffDocument(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaffDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublicDocumentByID = `-- name: GetPublicDocumentByID :one
SELECT id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE id = $1
  AND is_public = true
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $2::text[])
LIMIT 1
`

type GetPublicDocumentByIDParams struct {
	ID      string
	Column2 []string
}

type GetPublicDocumentByIDRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetPublicDocumentByID(ctx context.Context, arg GetPublicDocumentByIDParams) (GetPublicDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicDocumentByID, arg.ID, arg.Column2)
	var i GetPublicDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.ViewableTags,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffDocumentByID = `-- name: GetStaffDocumentByID :one
SELECT id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE id = $1
LIMIT 1
`

type GetStaffDocumentByIDRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetStaffDocumentByID(ctx context.Context, id string) (GetStaffDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStaffDocumentByID, id)
	var i GetStaffDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.ViewableTags,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicDocuments = `-- name: ListPublicDocuments :many
SELECT id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
WHERE is_public = true
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $1::text[])
ORDER BY updated_at DESC, id DESC
`

type ListPublicDocumentsRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPublicDocuments(ctx context.Context, dollar_1 []string) ([]ListPublicDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicDocuments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicDocumentsRow
	for rows.Next() {
		var i ListPublicDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.IsPublic,
			&i.ViewableTags,
			&i.IsImportant,
			&i.Filename,
			&i.MimeType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadDocumentIDsByUser = `-- name: ListReadDocumentIDsByUser :many
SELECT document_id
FROM document_reads
WHERE user_id = $1
  AND document_id = ANY($2::uuid[])
`

type ListReadDocumentIDsByUserParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListReadDocumentIDsByUser(ctx context.Context, arg ListReadDocumentIDsByUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReadDocumentIDsByUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffDocuments = `-- name: ListStaffDocuments :many
SELECT id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
FROM documents
ORDER BY updated_at DESC, id DESC
`

type ListStaffDocumentsRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListStaffDocuments(ctx context.Context) ([]ListStaffDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listStaffDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffDocumentsRow
	for rows.Next() {
		var i ListStaffDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.IsPublic,
			&i.ViewableTags,
			&i.IsImportant,
			&i.Filename,
			&i.MimeType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentRead = `-- name: MarkDocumentRead :exec
INSERT INTO document_reads (document_id, user_id)
VALUES ($1, $2)
ON CONFLICT (document_id, user_id) DO NOTHING
`

type MarkDocumentReadParams struct {
	DocumentID string
	UserID     string
}

func (q *Queries) MarkDocumentRead(ctx context.Context, arg MarkDocumentReadParams) error {
	_, err := q.db.Exec(ctx, markDocumentRead, arg.DocumentID, arg.UserID)
	return err
}

const updateStaffDocument = `-- name: UpdateStaffDocument :one
UPDATE documents
SET name = $2,
    description = $3,
    notes = $4,
    is_public = $5,
    viewable_tags = $6,
    is_important = $7,
    filename = $8,
    mime_type = $9,
    content = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, notes, is_public, viewable_tags, is_important, filename, mime_type, content, created_at, updated_at
`

type UpdateStaffDocumentParams struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
}

type UpdateStaffDocumentRow struct {
	ID           string
	Name         string
	Description  string
	Notes        string
	IsPublic     bool
	ViewableTags []string
	IsImportant  bool
	Filename     string
	MimeType     string
	Content      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateStaffDocument(ctx context.Context, arg UpdateStaffDocumentParams) (UpdateStaffDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateStaffDocument,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.IsPublic,
		arg.ViewableTags,
		arg.IsImportant,
		arg.Filename,
		arg.MimeType,
		arg.Content,
	)
	var i UpdateStaffDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.IsPublic,
		&i.ViewableTags,
		&i.IsImportant,
		&i.Filename,
		&i.MimeType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
