// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: form_questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormQuestionsByFormID = `-- name: CountFormQuestionsByFormID :one
SELECT COUNT(*)::bigint
FROM form_questions
WHERE form_id = $1
`

func (q *Queries) CountFormQuestionsByFormID(ctx context.Context, formID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFormQuestionsByFormID, formID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFormQuestion = `-- name: CreateFormQuestion :one
INSERT INTO form_questions (
    form_id,
    name,
    description,
    type,
    is_required,
    number_min,
    number_max,
    allowed_types,
    options,
    priority
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, form_id, name, description, type, is_required, number_min, number_max, allowed_types, options, priority, created_at, updated_at
`

type CreateFormQuestionParams struct {
	FormID       string
	Name         string
	Description  string
	Type         string
	IsRequired   bool
	NumberMin    pgtype.Int4
	NumberMax    pgtype.Int4
	AllowedTypes string
	Options      []byte
	Priority     int32
}

func (q *Queries) CreateFormQuestion(ctx context.Context, arg CreateFormQuestionParams) (FormQuestion, error) {
	row := q.db.QueryRow(ctx, createFormQuestion,
		arg.FormID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.IsRequired,
		arg.NumberMin,
		arg.NumberMax,
		arg.AllowedTypes,
		arg.Options,
		arg.Priority,
	)
	var i FormQuestion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.IsRequired,
		&i.NumberMin,
		&i.NumberMax,
		&i.AllowedTypes,
		&i.Options,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFormQuestion = `-- name: DeleteFormQuestion :execrows
DELETE FROM form_questions
WHERE id = $1
`

func (q *Queries) DeleteFormQuestion(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFormQuestion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFormQuestionsByFormID = `-- name: ListFormQuestionsByFormID :many
SELECT id, form_id, name, description, type, is_required, number_min, number_max, allowed_types, options, priority, created_at, updated_at
FROM form_questions
WHERE form_id = $1
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListFormQuestionsByFormID(ctx context.Context, formID string) ([]FormQuestion, error) {
	rows, err := q.db.Query(ctx, listFormQuestionsByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormQuestion
	for rows.Next() {
		var i FormQuestion
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.IsRequired,
			&i.NumberMin,
			&i.NumberMax,
			&i.AllowedTypes,
			&i.Options,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormQuestion = `-- name: UpdateFormQuestion :one
UPDATE form_questions
SET name = $2,
    description = $3,
    type = $4,
    is_required = $5,
    number_min = $6,
    number_max = $7,
    allowed_types = $8,
    options = $9,
    priority = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, form_id, name, description, type, is_required, number_min, number_max, allowed_types, options, priority, created_at, updated_at
`

type UpdateFormQuestionParams struct {
	ID           string
	Name         string
	Description  string
	Type         string
	IsRequired   bool
	NumberMin    pgtype.Int4
	NumberMax    pgtype.Int4
	AllowedTypes string
	Options      []byte
	Priority     int32
}

func (q *Queries) UpdateFormQuestion(ctx context.Context, arg UpdateFormQuestionParams) (FormQuestion, error) {
	row := q.db.QueryRow(ctx, updateFormQuestion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.IsRequired,
		arg.NumberMin,
		arg.NumberMax,
		arg.AllowedTypes,
		arg.Options,
		arg.Priority,
	)
	var i FormQuestion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.IsRequired,
		&i.NumberMin,
		&i.NumberMax,
		&i.AllowedTypes,
		&i.Options,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
