// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message)
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
`

type CreateFormParams struct {
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
}

type CreateFormRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (CreateFormRow, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.CircleID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.IsOpen,
		arg.OpenAt,
		arg.CloseAt,
		arg.MaxAnswers,
		arg.AnswerableTags,
		arg.ConfirmationMessage,
	)
	var i CreateFormRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :execrows
DELETE FROM forms
WHERE circle_id = $1
  AND id = $2
`

type DeleteFormParams struct {
	CircleID pgtype.Text
	ID       string
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForm, arg.CircleID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnyStaffFormByID = `-- name: GetAnyStaffFormByID :one
SELECT id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
FROM forms
WHERE id = $1
LIMIT 1
`

type GetAnyStaffFormByIDRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetAnyStaffFormByID(ctx context.Context, id string) (GetAnyStaffFormByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnyStaffFormByID, id)
	var i GetAnyStaffFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicOpenFormByID = `-- name: GetPublicOpenFormByID :one
SELECT id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
FROM forms
WHERE circle_id = $1
  AND id = $2
  AND is_public = true
  AND is_open = true
LIMIT 1
`

type GetPublicOpenFormByIDParams struct {
	CircleID pgtype.Text
	ID       string
}

type GetPublicOpenFormByIDRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetPublicOpenFormByID(ctx context.Context, arg GetPublicOpenFormByIDParams) (GetPublicOpenFormByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicOpenFormByID, arg.CircleID, arg.ID)
	var i GetPublicOpenFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffFormByID = `-- name: GetStaffFormByID :one
SELECT id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
FROM forms
WHERE circle_id = $1
  AND id = $2
LIMIT 1
`

type GetStaffFormByIDParams struct {
	CircleID pgtype.Text
	ID       string
}

type GetStaffFormByIDRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetStaffFormByID(ctx context.Context, arg GetStaffFormByIDParams) (GetStaffFormByIDRow, error) {
	row := q.db.QueryRow(ctx, getStaffFormByID, arg.CircleID, arg.ID)
	var i GetStaffFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicOpenFormsByCircle = `-- name: ListPublicOpenFormsByCircle :many
SELECT id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
FROM forms
WHERE circle_id = $1
  AND is_public = true
  AND is_open = true
ORDER BY close_at ASC, id ASC
`

type ListPublicOpenFormsByCircleRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ListPublicOpenFormsByCircle(ctx context.Context, circleID pgtype.Text) ([]ListPublicOpenFormsByCircleRow, error) {
	rows, err := q.db.Query(ctx, listPublicOpenFormsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicOpenFormsByCircleRow
	for rows.Next() {
		var i ListPublicOpenFormsByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.IsOpen,
			&i.OpenAt,
			&i.CloseAt,
			&i.MaxAnswers,
			&i.AnswerableTags,
			&i.ConfirmationMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffFormsByCircle = `-- name: ListStaffFormsByCircle :many
SELECT id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
FROM forms
WHERE circle_id = $1
ORDER BY close_at ASC, id ASC
`

type ListStaffFormsByCircleRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ListStaffFormsByCircle(ctx context.Context, circleID pgtype.Text) ([]ListStaffFormsByCircleRow, error) {
	rows, err := q.db.Query(ctx, listStaffFormsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffFormsByCircleRow
	for rows.Next() {
		var i ListStaffFormsByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.IsOpen,
			&i.OpenAt,
			&i.CloseAt,
			&i.MaxAnswers,
			&i.AnswerableTags,
			&i.ConfirmationMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnyFormByID = `-- name: UpdateAnyFormByID :one
UPDATE forms
SET name = $2,
    description = $3,
    is_public = $4,
    is_open = $5,
    open_at = $6,
    close_at = $7,
    updated_at = now(),
    max_answers = $8,
    answerable_tags = $9,
    confirmation_message = $10
WHERE id = $1
RETURNING id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
`

type UpdateAnyFormByIDParams struct {
	ID                  string
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
}

type UpdateAnyFormByIDRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateAnyFormByID(ctx context.Context, arg UpdateAnyFormByIDParams) (UpdateAnyFormByIDRow, error) {
	row := q.db.QueryRow(ctx, updateAnyFormByID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.IsOpen,
		arg.OpenAt,
		arg.CloseAt,
		arg.MaxAnswers,
		arg.AnswerableTags,
		arg.ConfirmationMessage,
	)
	var i UpdateAnyFormByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET name = $3,
    description = $4,
    is_public = $5,
    is_open = $6,
    open_at = $7,
    close_at = $8,
    updated_at = now(),
    max_answers = $9,
    answerable_tags = $10,
    confirmation_message = $11
WHERE circle_id = $1
  AND id = $2
RETURNING id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message, created_at, updated_at
`

type UpdateFormParams struct {
	CircleID            pgtype.Text
	ID                  string
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
}

type UpdateFormRow struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (UpdateFormRow, error) {
	row := q.db.QueryRow(ctx, updateForm,
		arg.CircleID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.IsOpen,
		arg.OpenAt,
		arg.CloseAt,
		arg.MaxAnswers,
		arg.AnswerableTags,
		arg.ConfirmationMessage,
	)
	var i UpdateFormRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.IsOpen,
		&i.OpenAt,
		&i.CloseAt,
		&i.MaxAnswers,
		&i.AnswerableTags,
		&i.ConfirmationMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
