// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMailJob = `-- name: CreateMailJob :one
INSERT INTO mail_jobs (circle_id, subject, body, recipients, created_by_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at
`

type CreateMailJobParams struct {
	CircleID        string
	Subject         string
	Body            string
	Recipients      []string
	CreatedByUserID string
}

func (q *Queries) CreateMailJob(ctx context.Context, arg CreateMailJobParams) (MailJob, error) {
	row := q.db.QueryRow(ctx, createMailJob,
		arg.CircleID,
		arg.Subject,
		arg.Body,
		arg.Recipients,
		arg.CreatedByUserID,
	)
	var i MailJob
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Subject,
		&i.Body,
		&i.Recipients,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const deleteMailJobsByCircle = `-- name: DeleteMailJobsByCircle :exec
DELETE FROM mail_jobs
WHERE circle_id = $1
`

func (q *Queries) DeleteMailJobsByCircle(ctx context.Context, circleID string) error {
	_, err := q.db.Exec(ctx, deleteMailJobsByCircle, circleID)
	return err
}

const listMailJobsByCircle = `-- name: ListMailJobsByCircle :many
SELECT id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at
FROM mail_jobs
WHERE circle_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMailJobsByCircle(ctx context.Context, circleID string) ([]MailJob, error) {
	rows, err := q.db.Query(ctx, listMailJobsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailJob
	for rows.Next() {
		var i MailJob
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Subject,
			&i.Body,
			&i.Recipients,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedMailJobs = `-- name: ListQueuedMailJobs :many
SELECT id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at
FROM mail_jobs
WHERE status = 'queued'
ORDER BY created_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListQueuedMailJobs(ctx context.Context, limit int32) ([]MailJob, error) {
	rows, err := q.db.Query(ctx, listQueuedMailJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailJob
	for rows.Next() {
		var i MailJob
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Subject,
			&i.Body,
			&i.Recipients,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailJobSent = `-- name: MarkMailJobSent :one
UPDATE mail_jobs
SET status = 'sent',
    delivered_at = $2
WHERE id = $1
RETURNING id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at
`

type MarkMailJobSentParams struct {
	ID          string
	DeliveredAt pgtype.Timestamptz
}

func (q *Queries) MarkMailJobSent(ctx context.Context, arg MarkMailJobSentParams) (MailJob, error) {
	row := q.db.QueryRow(ctx, markMailJobSent, arg.ID, arg.DeliveredAt)
	var i MailJob
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Subject,
		&i.Body,
		&i.Recipients,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
