// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMailJob = `-- name: CreateMailJob :one
INSERT INTO mail_jobs (circle_id, subject, body, recipients, created_by_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at, delivered_to
`

type CreateMailJobParams struct {
	CircleID        *string
	Subject         string
	Body            string
	Recipients      []string
	CreatedByUserID string
}

type CreateMailJobRow struct {
	ID              string
	CircleID        *string
	Subject         string
	Body            string
	Recipients      []string
	Status          string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	DeliveredAt     pgtype.Timestamptz
	DeliveredTo     []string
}

func (q *Queries) CreateMailJob(ctx context.Context, arg CreateMailJobParams) (CreateMailJobRow, error) {
	row := q.db.QueryRow(ctx, createMailJob,
		arg.CircleID,
		arg.Subject,
		arg.Body,
		arg.Recipients,
		arg.CreatedByUserID,
	)
	var i CreateMailJobRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Subject,
		&i.Body,
		&i.Recipients,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.DeliveredTo,
	)
	return i, err
}

const deleteMailJob = `-- name: DeleteMailJob :exec
DELETE FROM mail_jobs
WHERE id = $1
`

func (q *Queries) DeleteMailJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMailJob, id)
	return err
}

const deleteMailJobs = `-- name: DeleteMailJobs :exec
DELETE FROM mail_jobs
`

func (q *Queries) DeleteMailJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteMailJobs)
	return err
}

const deleteMailJobsByCircle = `-- name: DeleteMailJobsByCircle :exec
DELETE FROM mail_jobs
WHERE circle_id = $1
`

func (q *Queries) DeleteMailJobsByCircle(ctx context.Context, circleID *string) error {
	_, err := q.db.Exec(ctx, deleteMailJobsByCircle, circleID)
	return err
}

const listMailJobs = `-- name: ListMailJobs :many
SELECT id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at, delivered_to
FROM mail_jobs
ORDER BY created_at DESC, id DESC
`

type ListMailJobsRow struct {
	ID              string
	CircleID        *string
	Subject         string
	Body            string
	Recipients      []string
	Status          string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	DeliveredAt     pgtype.Timestamptz
	DeliveredTo     []string
}

func (q *Queries) ListMailJobs(ctx context.Context) ([]ListMailJobsRow, error) {
	rows, err := q.db.Query(ctx, listMailJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMailJobsRow
	for rows.Next() {
		var i ListMailJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Subject,
			&i.Body,
			&i.Recipients,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.DeliveredTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailJobsByCircle = `-- name: ListMailJobsByCircle :many
SELECT id, circle_id, subject, body, recipients, status, created_by_user_id, created_at, delivered_at, delivered_to
FROM mail_jobs
WHERE circle_id = $1
ORDER BY created_at DESC, id DESC
`

type ListMailJobsByCircleRow struct {
	ID              string
	CircleID        *string
	Subject         string
	Body            string
	Recipients      []string
	Status          string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	DeliveredAt     pgtype.Timestamptz
	DeliveredTo     []string
}

func (q *Queries) ListMailJobsByCircle(ctx context.Context, circleID *string) ([]ListMailJobsByCircleRow, error) {
	rows, err := q.db.Query(ctx, listMailJobsByCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMailJobsByCircleRow
	for rows.Next() {
		var i ListMailJobsByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Subject,
			&i.Body,
			&i.Recipients,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.DeliveredTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
