// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          string
	ActorUserID string
	Action      string
	TargetType  string
	TargetID    string
	CircleID    string
	Summary     string
	CreatedAt   pgtype.Timestamptz
}

type Answer struct {
	ID        string
	FormID    string
	CircleID  string
	Body      string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AnswerDetail struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	QuestionID string
	Value      string
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type AnswerUpload struct {
	ID         string
	AnswerID   string
	FormID     string
	CircleID   string
	Filename   string
	MimeType   string
	Content    []byte
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
	QuestionID pgtype.Text
}

type Booth struct {
	ID        string
	PlaceID   string
	CircleID  string
	CreatedAt pgtype.Timestamptz
}

type Circle struct {
	ID                    string
	Name                  string
	GroupName             string
	ParticipationTypeName string
	CreatedAt             pgtype.Timestamptz
	Tags                  []string
	ParticipationTypeID   pgtype.Text
	NameYomi              string
	GroupNameYomi         string
	InvitationToken       pgtype.Text
	SubmittedAt           pgtype.Timestamptz
	Notes                 string
	Status                string
	StatusReason          string
	StatusSetAt           pgtype.Timestamptz
	StatusSetBy           pgtype.Text
	CanChangeGroupName    bool
	UpdatedAt             pgtype.Timestamptz
}

type CircleUser struct {
	CircleID string
	UserID   string
	IsLeader bool
}

type ContactCategory struct {
	ID        string
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Document struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	IsPublic    bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	Notes       string
	IsImportant bool
	UpdatedAt   pgtype.Timestamptz
}

type Form struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
	UpdatedAt           pgtype.Timestamptz
}

type FormQuestion struct {
	ID           string
	FormID       string
	Name         string
	Description  string
	Type         string
	IsRequired   bool
	NumberMin    pgtype.Int4
	NumberMax    pgtype.Int4
	AllowedTypes string
	Options      []byte
	Priority     int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type MailJob struct {
	ID              string
	CircleID        pgtype.Text
	Subject         string
	Body            string
	Recipients      []string
	Status          string
	CreatedByUserID string
	CreatedAt       pgtype.Timestamptz
	DeliveredAt     pgtype.Timestamptz
}

type Page struct {
	ID           string
	Title        string
	Body         string
	IsPinned     bool
	IsPublic     bool
	PublishedAt  pgtype.Timestamptz
	Notes        string
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ParticipationType struct {
	ID            string
	Name          string
	Description   string
	UsersCountMin int32
	UsersCountMax int32
	Tags          []string
	FormID        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PendingRegistration struct {
	ID         string
	Univemail  string
	StudentID  string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Place struct {
	ID        string
	Name      string
	Type      int32
	Notes     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Read struct {
	PageID    string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID                 string
	UserID             string
	CsrfToken          string
	CurrentCircleID    pgtype.Text
	StaffAuthorized    bool
	StaffVerifyCode    string
	StaffVerifyExpires pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID                  string
	DisplayName         string
	Password            string
	CreatedAt           pgtype.Timestamptz
	IsVerified          bool
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	ContactEmail        string
	PhoneNumber         string
	IsEmailVerified     bool
	IsUnivemailVerified bool
}

type UserLoginID struct {
	LoginID string
	UserID  string
}

type UserPermission struct {
	UserID     string
	Permission string
	CreatedAt  pgtype.Timestamptz
}

type UserRole struct {
	UserID string
	Role   string
}
