// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (title, body, notes, is_pinned, is_public, viewable_tags, document_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
`

type CreatePageParams struct {
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
}

type CreatePageRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Title,
		arg.Body,
		arg.Notes,
		arg.IsPinned,
		arg.IsPublic,
		arg.ViewableTags,
		arg.DocumentIds,
	)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages
WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePageReads = `-- name: DeletePageReads :exec
DELETE FROM reads
WHERE page_id = $1
`

func (q *Queries) DeletePageReads(ctx context.Context, pageID string) error {
	_, err := q.db.Exec(ctx, deletePageReads, pageID)
	return err
}

const getGuestPageByID = `-- name: GetGuestPageByID :one
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE id = $1
  AND is_public = true
  AND is_pinned = false
  AND cardinality(viewable_tags) = 0
LIMIT 1
`

type GetGuestPageByIDRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetGuestPageByID(ctx context.Context, id string) (GetGuestPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getGuestPageByID, id)
	var i GetGuestPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByIDForCircle = `-- name: GetPageByIDForCircle :one
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE id = $2
  AND is_public = true
  AND is_pinned = false
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $1::text[])
LIMIT 1
`

type GetPageByIDForCircleParams struct {
	Column1 []string
	ID      string
}

type GetPageByIDForCircleRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetPageByIDForCircle(ctx context.Context, arg GetPageByIDForCircleParams) (GetPageByIDForCircleRow, error) {
	row := q.db.QueryRow(ctx, getPageByIDForCircle, arg.Column1, arg.ID)
	var i GetPageByIDForCircleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffPageByID = `-- name: GetStaffPageByID :one
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE id = $1
LIMIT 1
`

type GetStaffPageByIDRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetStaffPageByID(ctx context.Context, id string) (GetStaffPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getStaffPageByID, id)
	var i GetStaffPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuestPages = `-- name: ListGuestPages :many
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE is_public = true
  AND is_pinned = false
  AND cardinality(viewable_tags) = 0
  AND ($1 = '' OR lower(title || E'\n' || body) LIKE '%' || lower($1) || '%')
ORDER BY updated_at DESC, id DESC
`

type ListGuestPagesRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListGuestPages(ctx context.Context, dollar_1 interface{}) ([]ListGuestPagesRow, error) {
	rows, err := q.db.Query(ctx, listGuestPages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuestPagesRow
	for rows.Next() {
		var i ListGuestPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Notes,
			&i.IsPinned,
			&i.IsPublic,
			&i.ViewableTags,
			&i.DocumentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForCircle = `-- name: ListPagesForCircle :many
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE is_public = true
  AND is_pinned = false
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $1::text[])
  AND ($2 = '' OR lower(title || E'\n' || body) LIKE '%' || lower($2) || '%')
ORDER BY updated_at DESC, id DESC
`

type ListPagesForCircleParams struct {
	Column1 []string
	Column2 interface{}
}

type ListPagesForCircleRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListPagesForCircle(ctx context.Context, arg ListPagesForCircleParams) ([]ListPagesForCircleRow, error) {
	rows, err := q.db.Query(ctx, listPagesForCircle, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPagesForCircleRow
	for rows.Next() {
		var i ListPagesForCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Notes,
			&i.IsPinned,
			&i.IsPublic,
			&i.ViewableTags,
			&i.DocumentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadPageIDsByUser = `-- name: ListReadPageIDsByUser :many
SELECT page_id
FROM reads
WHERE user_id = $1
  AND page_id = ANY($2::text[])
`

type ListReadPageIDsByUserParams struct {
	UserID  string
	Column2 []string
}

func (q *Queries) ListReadPageIDsByUser(ctx context.Context, arg ListReadPageIDsByUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReadPageIDsByUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var page_id string
		if err := rows.Scan(&page_id); err != nil {
			return nil, err
		}
		items = append(items, page_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffPages = `-- name: ListStaffPages :many
SELECT id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
FROM pages
WHERE ($1 = '' OR lower(title || E'\n' || body) LIKE '%' || lower($1) || '%')
ORDER BY updated_at DESC, id DESC
`

type ListStaffPagesRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListStaffPages(ctx context.Context, dollar_1 interface{}) ([]ListStaffPagesRow, error) {
	rows, err := q.db.Query(ctx, listStaffPages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffPagesRow
	for rows.Next() {
		var i ListStaffPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Notes,
			&i.IsPinned,
			&i.IsPublic,
			&i.ViewableTags,
			&i.DocumentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchPagePin = `-- name: PatchPagePin :one
UPDATE pages
SET is_pinned = $2
WHERE id = $1
RETURNING id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
`

type PatchPagePinParams struct {
	ID       string
	IsPinned bool
}

type PatchPagePinRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) PatchPagePin(ctx context.Context, arg PatchPagePinParams) (PatchPagePinRow, error) {
	row := q.db.QueryRow(ctx, patchPagePin, arg.ID, arg.IsPinned)
	var i PatchPagePinRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = $2,
    body = $3,
    notes = $4,
    is_pinned = $5,
    is_public = $6,
    viewable_tags = $7,
    document_ids = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, created_at, updated_at
`

type UpdatePageParams struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
}

type UpdatePageRow struct {
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (UpdatePageRow, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Notes,
		arg.IsPinned,
		arg.IsPublic,
		arg.ViewableTags,
		arg.DocumentIds,
	)
	var i UpdatePageRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPageRead = `-- name: UpsertPageRead :exec
INSERT INTO reads (page_id, user_id)
VALUES ($1, $2)
ON CONFLICT (page_id, user_id) DO NOTHING
`

type UpsertPageReadParams struct {
	PageID string
	UserID string
}

func (q *Queries) UpsertPageRead(ctx context.Context, arg UpsertPageReadParams) error {
	_, err := q.db.Exec(ctx, upsertPageRead, arg.PageID, arg.UserID)
	return err
}
