// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
`

type CreatePageParams struct {
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
}

type CreatePageRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.CircleID,
		arg.Title,
		arg.Body,
		arg.Notes,
		arg.IsPinned,
		arg.IsPublic,
		arg.ViewableTags,
		arg.DocumentIds,
	)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.PublishedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages
WHERE circle_id = $1
  AND id = $2
`

type DeletePageParams struct {
	CircleID string
	ID       string
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, arg.CircleID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublicPageByID = `-- name: GetPublicPageByID :one
SELECT id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
FROM pages
WHERE circle_id = $1
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $2::text[])
  AND id = $3
  AND is_public = true
  AND is_pinned = false
LIMIT 1
`

type GetPublicPageByIDParams struct {
	CircleID string
	Column2  []string
	ID       string
}

type GetPublicPageByIDRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) GetPublicPageByID(ctx context.Context, arg GetPublicPageByIDParams) (GetPublicPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicPageByID, arg.CircleID, arg.Column2, arg.ID)
	var i GetPublicPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.PublishedAt,
	)
	return i, err
}

const getStaffPageByID = `-- name: GetStaffPageByID :one
SELECT id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
FROM pages
WHERE circle_id = $1
  AND id = $2
LIMIT 1
`

type GetStaffPageByIDParams struct {
	CircleID string
	ID       string
}

type GetStaffPageByIDRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) GetStaffPageByID(ctx context.Context, arg GetStaffPageByIDParams) (GetStaffPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getStaffPageByID, arg.CircleID, arg.ID)
	var i GetStaffPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.PublishedAt,
	)
	return i, err
}

const listPublicPagesByCircle = `-- name: ListPublicPagesByCircle :many
SELECT id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
FROM pages
WHERE circle_id = $1
  AND is_public = true
  AND is_pinned = false
  AND (cardinality(viewable_tags) = 0 OR viewable_tags && $2::text[])
  AND ($3 = '' OR lower(title || E'\n' || body) LIKE '%' || lower($3) || '%')
ORDER BY published_at DESC
`

type ListPublicPagesByCircleParams struct {
	CircleID string
	Column2  []string
	Column3  interface{}
}

type ListPublicPagesByCircleRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) ListPublicPagesByCircle(ctx context.Context, arg ListPublicPagesByCircleParams) ([]ListPublicPagesByCircleRow, error) {
	rows, err := q.db.Query(ctx, listPublicPagesByCircle, arg.CircleID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicPagesByCircleRow
	for rows.Next() {
		var i ListPublicPagesByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Title,
			&i.Body,
			&i.Notes,
			&i.IsPinned,
			&i.IsPublic,
			&i.ViewableTags,
			&i.DocumentIds,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffPagesByCircle = `-- name: ListStaffPagesByCircle :many
SELECT id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
FROM pages
WHERE circle_id = $1
  AND ($2 = '' OR lower(title || E'\n' || body) LIKE '%' || lower($2) || '%')
ORDER BY published_at DESC
`

type ListStaffPagesByCircleParams struct {
	CircleID string
	Column2  interface{}
}

type ListStaffPagesByCircleRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) ListStaffPagesByCircle(ctx context.Context, arg ListStaffPagesByCircleParams) ([]ListStaffPagesByCircleRow, error) {
	rows, err := q.db.Query(ctx, listStaffPagesByCircle, arg.CircleID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffPagesByCircleRow
	for rows.Next() {
		var i ListStaffPagesByCircleRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Title,
			&i.Body,
			&i.Notes,
			&i.IsPinned,
			&i.IsPublic,
			&i.ViewableTags,
			&i.DocumentIds,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchPagePin = `-- name: PatchPagePin :one
UPDATE pages
SET is_pinned = $3
WHERE circle_id = $1
  AND id = $2
RETURNING id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
`

type PatchPagePinParams struct {
	CircleID string
	ID       string
	IsPinned bool
}

type PatchPagePinRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) PatchPagePin(ctx context.Context, arg PatchPagePinParams) (PatchPagePinRow, error) {
	row := q.db.QueryRow(ctx, patchPagePin, arg.CircleID, arg.ID, arg.IsPinned)
	var i PatchPagePinRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.PublishedAt,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = $3,
    body = $4,
    notes = $5,
    is_pinned = $6,
    is_public = $7,
    viewable_tags = $8,
    document_ids = $9
WHERE circle_id = $1
  AND id = $2
RETURNING id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at
`

type UpdatePageParams struct {
	CircleID     string
	ID           string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
}

type UpdatePageRow struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (UpdatePageRow, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.CircleID,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Notes,
		arg.IsPinned,
		arg.IsPublic,
		arg.ViewableTags,
		arg.DocumentIds,
	)
	var i UpdatePageRow
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Title,
		&i.Body,
		&i.Notes,
		&i.IsPinned,
		&i.IsPublic,
		&i.ViewableTags,
		&i.DocumentIds,
		&i.PublishedAt,
	)
	return i, err
}
