// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participation_types.sql

package db

import (
	"context"
)

const createParticipationType = `-- name: CreateParticipationType :one
INSERT INTO participation_types (id, name, description, users_count_min, users_count_max, tags, form_id)
VALUES (uuidv7(), $1, $2, $3, $4, $5, $6)
RETURNING id, name, description, users_count_min, users_count_max, tags, form_id, created_at, updated_at
`

type CreateParticipationTypeParams struct {
	Name          string
	Description   string
	UsersCountMin int32
	UsersCountMax int32
	Tags          []string
	FormID        string
}

func (q *Queries) CreateParticipationType(ctx context.Context, arg CreateParticipationTypeParams) (ParticipationType, error) {
	row := q.db.QueryRow(ctx, createParticipationType,
		arg.Name,
		arg.Description,
		arg.UsersCountMin,
		arg.UsersCountMax,
		arg.Tags,
		arg.FormID,
	)
	var i ParticipationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsersCountMin,
		&i.UsersCountMax,
		&i.Tags,
		&i.FormID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParticipationType = `-- name: DeleteParticipationType :execrows
DELETE FROM participation_types
WHERE id = $1
`

func (q *Queries) DeleteParticipationType(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParticipationType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParticipationTypeByFormID = `-- name: GetParticipationTypeByFormID :one
SELECT id, name, description, users_count_min, users_count_max, tags, form_id, created_at, updated_at
FROM participation_types
WHERE form_id = $1
LIMIT 1
`

func (q *Queries) GetParticipationTypeByFormID(ctx context.Context, formID string) (ParticipationType, error) {
	row := q.db.QueryRow(ctx, getParticipationTypeByFormID, formID)
	var i ParticipationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsersCountMin,
		&i.UsersCountMax,
		&i.Tags,
		&i.FormID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipationTypeByID = `-- name: GetParticipationTypeByID :one
SELECT id, name, description, users_count_min, users_count_max, tags, form_id, created_at, updated_at
FROM participation_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetParticipationTypeByID(ctx context.Context, id string) (ParticipationType, error) {
	row := q.db.QueryRow(ctx, getParticipationTypeByID, id)
	var i ParticipationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsersCountMin,
		&i.UsersCountMax,
		&i.Tags,
		&i.FormID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParticipationTypes = `-- name: ListParticipationTypes :many
SELECT id, name, description, users_count_min, users_count_max, tags, form_id, created_at, updated_at
FROM participation_types
ORDER BY name ASC, id ASC
`

func (q *Queries) ListParticipationTypes(ctx context.Context) ([]ParticipationType, error) {
	rows, err := q.db.Query(ctx, listParticipationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParticipationType
	for rows.Next() {
		var i ParticipationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UsersCountMin,
			&i.UsersCountMax,
			&i.Tags,
			&i.FormID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipationType = `-- name: UpdateParticipationType :one
UPDATE participation_types
SET name = $2,
    description = $3,
    users_count_min = $4,
    users_count_max = $5,
    tags = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, users_count_min, users_count_max, tags, form_id, created_at, updated_at
`

type UpdateParticipationTypeParams struct {
	ID            string
	Name          string
	Description   string
	UsersCountMin int32
	UsersCountMax int32
	Tags          []string
}

func (q *Queries) UpdateParticipationType(ctx context.Context, arg UpdateParticipationTypeParams) (ParticipationType, error) {
	row := q.db.QueryRow(ctx, updateParticipationType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UsersCountMin,
		arg.UsersCountMax,
		arg.Tags,
	)
	var i ParticipationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UsersCountMin,
		&i.UsersCountMax,
		&i.Tags,
		&i.FormID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
