// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package db

import (
	"context"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (name, type, notes)
VALUES ($1, $2, $3)
RETURNING id, name, type, notes, created_at, updated_at
`

type CreatePlaceParams struct {
	Name  string
	Type  int32
	Notes string
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, createPlace, arg.Name, arg.Type, arg.Notes)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlace = `-- name: DeletePlace :execrows
DELETE FROM places
WHERE id = $1
`

func (q *Queries) DeletePlace(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT id, name, type, notes, created_at, updated_at
FROM places
ORDER BY name ASC
`

func (q *Queries) ListPlaces(ctx context.Context) ([]Place, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places
SET name = $2,
    type = $3,
    notes = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, type, notes, created_at, updated_at
`

type UpdatePlaceParams struct {
	ID    string
	Name  string
	Type  int32
	Notes string
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Notes,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
