// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seedDeleteCircleUserByUserID = `-- name: SeedDeleteCircleUserByUserID :exec
DELETE FROM circle_user WHERE user_id = $1
`

func (q *Queries) SeedDeleteCircleUserByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, seedDeleteCircleUserByUserID, userID)
	return err
}

const seedUpsertBooth = `-- name: SeedUpsertBooth :exec
INSERT INTO booths (place_id, circle_id)
VALUES ($1, $2)
ON CONFLICT (place_id, circle_id) DO NOTHING
`

type SeedUpsertBoothParams struct {
	PlaceID  string
	CircleID string
}

func (q *Queries) SeedUpsertBooth(ctx context.Context, arg SeedUpsertBoothParams) error {
	_, err := q.db.Exec(ctx, seedUpsertBooth, arg.PlaceID, arg.CircleID)
	return err
}

const seedUpsertCircle = `-- name: SeedUpsertCircle :exec
INSERT INTO circles (id, name, name_yomi, group_name, group_name_yomi, participation_type_id, participation_type_name, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    name_yomi = EXCLUDED.name_yomi,
    group_name = EXCLUDED.group_name,
    group_name_yomi = EXCLUDED.group_name_yomi,
    participation_type_id = EXCLUDED.participation_type_id,
    participation_type_name = EXCLUDED.participation_type_name,
    tags = EXCLUDED.tags
`

type SeedUpsertCircleParams struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeID   pgtype.Text
	ParticipationTypeName string
	Tags                  []string
}

func (q *Queries) SeedUpsertCircle(ctx context.Context, arg SeedUpsertCircleParams) error {
	_, err := q.db.Exec(ctx, seedUpsertCircle,
		arg.ID,
		arg.Name,
		arg.NameYomi,
		arg.GroupName,
		arg.GroupNameYomi,
		arg.ParticipationTypeID,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	return err
}

const seedUpsertCircleUser = `-- name: SeedUpsertCircleUser :exec
INSERT INTO circle_user (circle_id, user_id, is_leader)
VALUES ($1, $2, $3)
ON CONFLICT (circle_id, user_id) DO UPDATE
SET is_leader = EXCLUDED.is_leader
`

type SeedUpsertCircleUserParams struct {
	CircleID string
	UserID   string
	IsLeader bool
}

func (q *Queries) SeedUpsertCircleUser(ctx context.Context, arg SeedUpsertCircleUserParams) error {
	_, err := q.db.Exec(ctx, seedUpsertCircleUser, arg.CircleID, arg.UserID, arg.IsLeader)
	return err
}

const seedUpsertCircleWithoutParticipationType = `-- name: SeedUpsertCircleWithoutParticipationType :exec
INSERT INTO circles (id, name, name_yomi, group_name, group_name_yomi, participation_type_name, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type SeedUpsertCircleWithoutParticipationTypeParams struct {
	ID                    string
	Name                  string
	NameYomi              string
	GroupName             string
	GroupNameYomi         string
	ParticipationTypeName string
	Tags                  []string
}

func (q *Queries) SeedUpsertCircleWithoutParticipationType(ctx context.Context, arg SeedUpsertCircleWithoutParticipationTypeParams) error {
	_, err := q.db.Exec(ctx, seedUpsertCircleWithoutParticipationType,
		arg.ID,
		arg.Name,
		arg.NameYomi,
		arg.GroupName,
		arg.GroupNameYomi,
		arg.ParticipationTypeName,
		arg.Tags,
	)
	return err
}

const seedUpsertContactCategory = `-- name: SeedUpsertContactCategory :exec
INSERT INTO contact_categories (id, name, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    email = EXCLUDED.email,
    updated_at = now()
`

type SeedUpsertContactCategoryParams struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) SeedUpsertContactCategory(ctx context.Context, arg SeedUpsertContactCategoryParams) error {
	_, err := q.db.Exec(ctx, seedUpsertContactCategory, arg.ID, arg.Name, arg.Email)
	return err
}

const seedUpsertDocument = `-- name: SeedUpsertDocument :exec
INSERT INTO documents (id, circle_id, name, description, notes, is_public, is_important, filename, mime_type, content, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE
SET circle_id = EXCLUDED.circle_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    notes = EXCLUDED.notes,
    is_public = EXCLUDED.is_public,
    is_important = EXCLUDED.is_important,
    filename = EXCLUDED.filename,
    mime_type = EXCLUDED.mime_type,
    content = EXCLUDED.content,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
`

type SeedUpsertDocumentParams struct {
	ID          string
	CircleID    string
	Name        string
	Description string
	Notes       string
	IsPublic    bool
	IsImportant bool
	Filename    string
	MimeType    string
	Content     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SeedUpsertDocument(ctx context.Context, arg SeedUpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, seedUpsertDocument,
		arg.ID,
		arg.CircleID,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.IsPublic,
		arg.IsImportant,
		arg.Filename,
		arg.MimeType,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedUpsertForm = `-- name: SeedUpsertForm :exec
INSERT INTO forms (id, circle_id, name, description, is_public, is_open, open_at, close_at, max_answers, answerable_tags, confirmation_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE
SET circle_id = EXCLUDED.circle_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_public = EXCLUDED.is_public,
    is_open = EXCLUDED.is_open,
    open_at = EXCLUDED.open_at,
    close_at = EXCLUDED.close_at,
    max_answers = EXCLUDED.max_answers,
    answerable_tags = EXCLUDED.answerable_tags,
    confirmation_message = EXCLUDED.confirmation_message
`

type SeedUpsertFormParams struct {
	ID                  string
	CircleID            pgtype.Text
	Name                string
	Description         string
	IsPublic            bool
	IsOpen              bool
	OpenAt              pgtype.Timestamptz
	CloseAt             pgtype.Timestamptz
	MaxAnswers          int32
	AnswerableTags      []string
	ConfirmationMessage string
}

func (q *Queries) SeedUpsertForm(ctx context.Context, arg SeedUpsertFormParams) error {
	_, err := q.db.Exec(ctx, seedUpsertForm,
		arg.ID,
		arg.CircleID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.IsOpen,
		arg.OpenAt,
		arg.CloseAt,
		arg.MaxAnswers,
		arg.AnswerableTags,
		arg.ConfirmationMessage,
	)
	return err
}

const seedUpsertPage = `-- name: SeedUpsertPage :exec
INSERT INTO pages (id, circle_id, title, body, notes, is_pinned, is_public, viewable_tags, document_ids, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE
SET circle_id = EXCLUDED.circle_id,
    title = EXCLUDED.title,
    body = EXCLUDED.body,
    notes = EXCLUDED.notes,
    is_pinned = EXCLUDED.is_pinned,
    is_public = EXCLUDED.is_public,
    viewable_tags = EXCLUDED.viewable_tags,
    document_ids = EXCLUDED.document_ids,
    published_at = EXCLUDED.published_at
`

type SeedUpsertPageParams struct {
	ID           string
	CircleID     string
	Title        string
	Body         string
	Notes        string
	IsPinned     bool
	IsPublic     bool
	ViewableTags []string
	DocumentIds  []string
	PublishedAt  pgtype.Timestamptz
}

func (q *Queries) SeedUpsertPage(ctx context.Context, arg SeedUpsertPageParams) error {
	_, err := q.db.Exec(ctx, seedUpsertPage,
		arg.ID,
		arg.CircleID,
		arg.Title,
		arg.Body,
		arg.Notes,
		arg.IsPinned,
		arg.IsPublic,
		arg.ViewableTags,
		arg.DocumentIds,
		arg.PublishedAt,
	)
	return err
}

const seedUpsertParticipationType = `-- name: SeedUpsertParticipationType :exec
INSERT INTO participation_types (id, name, description, users_count_min, users_count_max, tags, form_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    users_count_min = EXCLUDED.users_count_min,
    users_count_max = EXCLUDED.users_count_max,
    tags = EXCLUDED.tags,
    form_id = EXCLUDED.form_id,
    updated_at = now()
`

type SeedUpsertParticipationTypeParams struct {
	ID            string
	Name          string
	Description   string
	UsersCountMin int32
	UsersCountMax int32
	Tags          []string
	FormID        string
}

func (q *Queries) SeedUpsertParticipationType(ctx context.Context, arg SeedUpsertParticipationTypeParams) error {
	_, err := q.db.Exec(ctx, seedUpsertParticipationType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UsersCountMin,
		arg.UsersCountMax,
		arg.Tags,
		arg.FormID,
	)
	return err
}

const seedUpsertPlace = `-- name: SeedUpsertPlace :exec
INSERT INTO places (id, name, type, notes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    type = EXCLUDED.type,
    notes = EXCLUDED.notes,
    updated_at = now()
`

type SeedUpsertPlaceParams struct {
	ID    string
	Name  string
	Type  int32
	Notes string
}

func (q *Queries) SeedUpsertPlace(ctx context.Context, arg SeedUpsertPlaceParams) error {
	_, err := q.db.Exec(ctx, seedUpsertPlace,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Notes,
	)
	return err
}

const seedUpsertTag = `-- name: SeedUpsertTag :exec
INSERT INTO tags (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = now()
`

type SeedUpsertTagParams struct {
	ID   string
	Name string
}

func (q *Queries) SeedUpsertTag(ctx context.Context, arg SeedUpsertTagParams) error {
	_, err := q.db.Exec(ctx, seedUpsertTag, arg.ID, arg.Name)
	return err
}

const seedUpsertUser = `-- name: SeedUpsertUser :exec
INSERT INTO users (id, display_name, password, is_verified)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET display_name = EXCLUDED.display_name,
    password = EXCLUDED.password,
    is_verified = EXCLUDED.is_verified
`

type SeedUpsertUserParams struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
}

func (q *Queries) SeedUpsertUser(ctx context.Context, arg SeedUpsertUserParams) error {
	_, err := q.db.Exec(ctx, seedUpsertUser,
		arg.ID,
		arg.DisplayName,
		arg.Password,
		arg.IsVerified,
	)
	return err
}
