// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id,
    user_id,
    csrf_token,
    current_circle_id,
    staff_authorized,
    staff_verify_code,
    staff_verify_expires
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID                 string
	UserID             string
	CsrfToken          string
	CurrentCircleID    pgtype.Text
	StaffAuthorized    bool
	StaffVerifyCode    string
	StaffVerifyExpires pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.CurrentCircleID,
		arg.StaffAuthorized,
		arg.StaffVerifyCode,
		arg.StaffVerifyExpires,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, csrf_token, current_circle_id, staff_authorized, staff_verify_code, staff_verify_expires, created_at, updated_at
FROM sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.CurrentCircleID,
		&i.StaffAuthorized,
		&i.StaffVerifyCode,
		&i.StaffVerifyExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET current_circle_id = $2,
    staff_authorized = $3,
    staff_verify_code = $4,
    staff_verify_expires = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID                 string
	CurrentCircleID    pgtype.Text
	StaffAuthorized    bool
	StaffVerifyCode    string
	StaffVerifyExpires pgtype.Timestamptz
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.CurrentCircleID,
		arg.StaffAuthorized,
		arg.StaffVerifyCode,
		arg.StaffVerifyExpires,
	)
	return err
}
