// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserLoginID = `-- name: AddUserLoginID :exec
INSERT INTO user_login_ids (login_id, user_id)
VALUES ($1, $2)
`

type AddUserLoginIDParams struct {
	LoginID string
	UserID  string
}

func (q *Queries) AddUserLoginID(ctx context.Context, arg AddUserLoginIDParams) error {
	_, err := q.db.Exec(ctx, addUserLoginID, arg.LoginID, arg.UserID)
	return err
}

const addUserPermission = `-- name: AddUserPermission :exec
INSERT INTO user_permissions (user_id, permission)
VALUES ($1, $2)
ON CONFLICT (user_id, permission) DO NOTHING
`

type AddUserPermissionParams struct {
	UserID     string
	Permission string
}

func (q *Queries) AddUserPermission(ctx context.Context, arg AddUserPermissionParams) error {
	_, err := q.db.Exec(ctx, addUserPermission, arg.UserID, arg.Permission)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id, role) DO NOTHING
`

type AddUserRoleParams struct {
	UserID string
	Role   string
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.Role)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    last_name,
    last_name_reading,
    first_name,
    first_name_reading,
    display_name,
    contact_email,
    phone_number,
    password,
    is_verified,
    is_email_verified,
    is_univemail_verified
) VALUES (
    COALESCE(NULLIF($1, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, last_name, last_name_reading, first_name, first_name_reading, display_name, contact_email, phone_number, password, is_verified, is_email_verified, is_univemail_verified, created_at
`

type CreateUserParams struct {
	Column1             interface{}
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	Password            string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
}

type CreateUserRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	Password            string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Column1,
		arg.LastName,
		arg.LastNameReading,
		arg.FirstName,
		arg.FirstNameReading,
		arg.DisplayName,
		arg.ContactEmail,
		arg.PhoneNumber,
		arg.Password,
		arg.IsVerified,
		arg.IsEmailVerified,
		arg.IsUnivemailVerified,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.LastNameReading,
		&i.FirstName,
		&i.FirstNameReading,
		&i.DisplayName,
		&i.ContactEmail,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.IsEmailVerified,
		&i.IsUnivemailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserLoginIDs = `-- name: DeleteUserLoginIDs :exec
DELETE FROM user_login_ids
WHERE user_id = $1
`

func (q *Queries) DeleteUserLoginIDs(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserLoginIDs, userID)
	return err
}

const deleteUserPermissions = `-- name: DeleteUserPermissions :exec
DELETE FROM user_permissions
WHERE user_id = $1
`

func (q *Queries) DeleteUserPermissions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserPermissions, userID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUserByAuthIdentifier = `-- name: GetUserByAuthIdentifier :one
SELECT DISTINCT users.id, users.display_name, users.password, users.is_verified, users.created_at
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
WHERE lower(user_login_ids.login_id) = lower($1)
   OR lower(users.contact_email) = lower($1)
LIMIT 1
`

type GetUserByAuthIdentifierRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByAuthIdentifier(ctx context.Context, lower string) (GetUserByAuthIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthIdentifier, lower)
	var i GetUserByAuthIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByContactEmail = `-- name: GetUserByContactEmail :one
SELECT id, display_name, password, is_verified, created_at
FROM users
WHERE lower(contact_email) = lower($1)
LIMIT 1
`

type GetUserByContactEmailRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByContactEmail(ctx context.Context, lower string) (GetUserByContactEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByContactEmail, lower)
	var i GetUserByContactEmailRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, password, is_verified, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLoginID = `-- name: GetUserByLoginID :one
SELECT users.id, users.display_name, users.password, users.is_verified, users.created_at
FROM users
JOIN user_login_ids ON user_login_ids.user_id = users.id
WHERE user_login_ids.login_id = $1
LIMIT 1
`

type GetUserByLoginIDRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByLoginID(ctx context.Context, loginID string) (GetUserByLoginIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByLoginID, loginID)
	var i GetUserByLoginIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithRelationsByID = `-- name: GetUserWithRelationsByID :one
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL AND circle_user.is_leader),
        ARRAY[]::text[]
    )::text[] AS leader_circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
WHERE users.id = $1
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
`

type GetUserWithRelationsByIDRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
	LeaderCircleIds     []string
}

func (q *Queries) GetUserWithRelationsByID(ctx context.Context, id string) (GetUserWithRelationsByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRelationsByID, id)
	var i GetUserWithRelationsByIDRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.LastNameReading,
		&i.FirstName,
		&i.FirstNameReading,
		&i.DisplayName,
		&i.ContactEmail,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.IsEmailVerified,
		&i.IsUnivemailVerified,
		&i.LoginIds,
		&i.Roles,
		&i.Permissions,
		&i.CircleIds,
		&i.LeaderCircleIds,
	)
	return i, err
}

const listCircleLeadersByCircleIDs = `-- name: ListCircleLeadersByCircleIDs :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE circle_user.is_leader = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListCircleLeadersByCircleIDsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
}

func (q *Queries) ListCircleLeadersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListCircleLeadersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listCircleLeadersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCircleLeadersByCircleIDsRow
	for rows.Next() {
		var i ListCircleLeadersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLoginIDs = `-- name: ListUserLoginIDs :many
SELECT login_id
FROM user_login_ids
WHERE user_id = $1
ORDER BY login_id
`

func (q *Queries) ListUserLoginIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserLoginIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login_id string
		if err := rows.Scan(&login_id); err != nil {
			return nil, err
		}
		items = append(items, login_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT permission
FROM user_permissions
WHERE user_id = $1
ORDER BY permission
`

func (q *Queries) ListUserPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role
FROM user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, password, is_verified, created_at
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Password,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCircleIDs = `-- name: ListUsersByCircleIDs :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL AND circle_user.is_leader),
        ARRAY[]::text[]
    )::text[] AS leader_circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListUsersByCircleIDsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
	LeaderCircleIds     []string
}

func (q *Queries) ListUsersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListUsersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listUsersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByCircleIDsRow
	for rows.Next() {
		var i ListUsersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
			&i.LeaderCircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithQuery = `-- name: ListUsersWithQuery :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL AND circle_user.is_leader),
        ARRAY[]::text[]
    )::text[] AS leader_circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
WHERE ($1::text = '' OR
    users.id ILIKE '%' || $1 || '%' OR
    users.display_name ILIKE '%' || $1 || '%' OR
    users.last_name ILIKE '%' || $1 || '%' OR
    users.first_name ILIKE '%' || $1 || '%' OR
    users.contact_email ILIKE '%' || $1 || '%' OR
    EXISTS (SELECT 1 FROM user_login_ids AS li WHERE li.user_id = users.id AND li.login_id ILIKE '%' || $1 || '%')
)
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListUsersWithQueryRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
	LeaderCircleIds     []string
}

func (q *Queries) ListUsersWithQuery(ctx context.Context, dollar_1 string) ([]ListUsersWithQueryRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithQuery, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithQueryRow
	for rows.Next() {
		var i ListUsersWithQueryRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
			&i.LeaderCircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRelations = `-- name: ListUsersWithRelations :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL AND circle_user.is_leader),
        ARRAY[]::text[]
    )::text[] AS leader_circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListUsersWithRelationsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
	LeaderCircleIds     []string
}

func (q *Queries) ListUsersWithRelations(ctx context.Context) ([]ListUsersWithRelationsRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRelationsRow
	for rows.Next() {
		var i ListUsersWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
			&i.LeaderCircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedCircleLeadersByCircleIDs = `-- name: ListVerifiedCircleLeadersByCircleIDs :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
  AND circle_user.is_leader = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListVerifiedCircleLeadersByCircleIDsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
}

func (q *Queries) ListVerifiedCircleLeadersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListVerifiedCircleLeadersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedCircleLeadersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedCircleLeadersByCircleIDsRow
	for rows.Next() {
		var i ListVerifiedCircleLeadersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedUsersByCircleIDs = `-- name: ListVerifiedUsersByCircleIDs :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListVerifiedUsersByCircleIDsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
}

func (q *Queries) ListVerifiedUsersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListVerifiedUsersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedUsersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedUsersByCircleIDsRow
	for rows.Next() {
		var i ListVerifiedUsersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedUsersWithRelations = `-- name: ListVerifiedUsersWithRelations :many
SELECT
    users.id,
    users.last_name,
    users.last_name_reading,
    users.first_name,
    users.first_name_reading,
    users.display_name,
    users.contact_email,
    users.phone_number,
    users.is_verified,
    users.is_email_verified,
    users.is_univemail_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL AND circle_user.is_leader),
        ARRAY[]::text[]
    )::text[] AS leader_circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
GROUP BY users.id, users.last_name, users.last_name_reading, users.first_name, users.first_name_reading,
         users.display_name, users.contact_email, users.phone_number, users.is_verified, users.is_email_verified,
         users.is_univemail_verified
ORDER BY users.id
`

type ListVerifiedUsersWithRelationsRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	LoginIds            []string
	Roles               []string
	Permissions         []string
	CircleIds           []string
	LeaderCircleIds     []string
}

func (q *Queries) ListVerifiedUsersWithRelations(ctx context.Context) ([]ListVerifiedUsersWithRelationsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedUsersWithRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedUsersWithRelationsRow
	for rows.Next() {
		var i ListVerifiedUsersWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.LastNameReading,
			&i.FirstName,
			&i.FirstNameReading,
			&i.DisplayName,
			&i.ContactEmail,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.IsEmailVerified,
			&i.IsUnivemailVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
			&i.LeaderCircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserDisplayNameParams struct {
	ID          string
	DisplayName string
}

type UpdateUserDisplayNameRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserEmailVerification = `-- name: UpdateUserEmailVerification :one
UPDATE users
SET is_email_verified = $2,
    is_verified = $2 AND is_univemail_verified
WHERE id = $1
RETURNING id, last_name, last_name_reading, first_name, first_name_reading, display_name, contact_email, phone_number, password, is_verified, is_email_verified, is_univemail_verified, created_at
`

type UpdateUserEmailVerificationParams struct {
	ID              string
	IsEmailVerified bool
}

type UpdateUserEmailVerificationRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	Password            string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateUserEmailVerification(ctx context.Context, arg UpdateUserEmailVerificationParams) (UpdateUserEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmailVerification, arg.ID, arg.IsEmailVerified)
	var i UpdateUserEmailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.LastNameReading,
		&i.FirstName,
		&i.FirstNameReading,
		&i.DisplayName,
		&i.ContactEmail,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.IsEmailVerified,
		&i.IsUnivemailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserIsVerified = `-- name: UpdateUserIsVerified :one
UPDATE users
SET is_verified = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserIsVerifiedParams struct {
	ID         string
	IsVerified bool
}

type UpdateUserIsVerifiedRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserIsVerified(ctx context.Context, arg UpdateUserIsVerifiedParams) (UpdateUserIsVerifiedRow, error) {
	row := q.db.QueryRow(ctx, updateUserIsVerified, arg.ID, arg.IsVerified)
	var i UpdateUserIsVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserPasswordParams struct {
	ID       string
	Password string
}

type UpdateUserPasswordRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET last_name = $2,
    last_name_reading = $3,
    first_name = $4,
    first_name_reading = $5,
    contact_email = $6,
    phone_number = $7
WHERE id = $1
RETURNING id, last_name, last_name_reading, first_name, first_name_reading, display_name, contact_email, phone_number, password, is_verified, is_email_verified, is_univemail_verified, created_at
`

type UpdateUserProfileParams struct {
	ID               string
	LastName         string
	LastNameReading  string
	FirstName        string
	FirstNameReading string
	ContactEmail     string
	PhoneNumber      string
}

type UpdateUserProfileRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	Password            string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.LastName,
		arg.LastNameReading,
		arg.FirstName,
		arg.FirstNameReading,
		arg.ContactEmail,
		arg.PhoneNumber,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.LastNameReading,
		&i.FirstName,
		&i.FirstNameReading,
		&i.DisplayName,
		&i.ContactEmail,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.IsEmailVerified,
		&i.IsUnivemailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserUnivemailVerification = `-- name: UpdateUserUnivemailVerification :one
UPDATE users
SET is_univemail_verified = $2,
    is_verified = is_email_verified AND $2
WHERE id = $1
RETURNING id, last_name, last_name_reading, first_name, first_name_reading, display_name, contact_email, phone_number, password, is_verified, is_email_verified, is_univemail_verified, created_at
`

type UpdateUserUnivemailVerificationParams struct {
	ID                  string
	IsUnivemailVerified bool
}

type UpdateUserUnivemailVerificationRow struct {
	ID                  string
	LastName            string
	LastNameReading     string
	FirstName           string
	FirstNameReading    string
	DisplayName         string
	ContactEmail        string
	PhoneNumber         string
	Password            string
	IsVerified          bool
	IsEmailVerified     bool
	IsUnivemailVerified bool
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateUserUnivemailVerification(ctx context.Context, arg UpdateUserUnivemailVerificationParams) (UpdateUserUnivemailVerificationRow, error) {
	row := q.db.QueryRow(ctx, updateUserUnivemailVerification, arg.ID, arg.IsUnivemailVerified)
	var i UpdateUserUnivemailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.LastNameReading,
		&i.FirstName,
		&i.FirstNameReading,
		&i.DisplayName,
		&i.ContactEmail,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.IsEmailVerified,
		&i.IsUnivemailVerified,
		&i.CreatedAt,
	)
	return i, err
}
