// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserLoginID = `-- name: AddUserLoginID :exec
INSERT INTO user_login_ids (login_id, user_id)
VALUES ($1, $2)
ON CONFLICT (login_id) DO UPDATE
SET user_id = EXCLUDED.user_id
`

type AddUserLoginIDParams struct {
	LoginID string
	UserID  string
}

func (q *Queries) AddUserLoginID(ctx context.Context, arg AddUserLoginIDParams) error {
	_, err := q.db.Exec(ctx, addUserLoginID, arg.LoginID, arg.UserID)
	return err
}

const addUserPermission = `-- name: AddUserPermission :exec
INSERT INTO user_permissions (user_id, permission)
VALUES ($1, $2)
ON CONFLICT (user_id, permission) DO NOTHING
`

type AddUserPermissionParams struct {
	UserID     string
	Permission string
}

func (q *Queries) AddUserPermission(ctx context.Context, arg AddUserPermissionParams) error {
	_, err := q.db.Exec(ctx, addUserPermission, arg.UserID, arg.Permission)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id, role) DO NOTHING
`

type AddUserRoleParams struct {
	UserID string
	Role   string
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.Role)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserLoginIDs = `-- name: DeleteUserLoginIDs :exec
DELETE FROM user_login_ids
WHERE user_id = $1
`

func (q *Queries) DeleteUserLoginIDs(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserLoginIDs, userID)
	return err
}

const deleteUserPermissions = `-- name: DeleteUserPermissions :exec
DELETE FROM user_permissions
WHERE user_id = $1
`

func (q *Queries) DeleteUserPermissions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserPermissions, userID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, password, is_verified, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLoginID = `-- name: GetUserByLoginID :one
SELECT users.id, users.display_name, users.password, users.is_verified, users.created_at
FROM users
JOIN user_login_ids ON user_login_ids.user_id = users.id
WHERE user_login_ids.login_id = $1
LIMIT 1
`

type GetUserByLoginIDRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByLoginID(ctx context.Context, loginID string) (GetUserByLoginIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByLoginID, loginID)
	var i GetUserByLoginIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithRelationsByID = `-- name: GetUserWithRelationsByID :one
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
WHERE users.id = $1
GROUP BY users.id, users.display_name, users.is_verified
`

type GetUserWithRelationsByIDRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) GetUserWithRelationsByID(ctx context.Context, id string) (GetUserWithRelationsByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRelationsByID, id)
	var i GetUserWithRelationsByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsVerified,
		&i.LoginIds,
		&i.Roles,
		&i.Permissions,
		&i.CircleIds,
	)
	return i, err
}

const listCircleLeadersByCircleIDs = `-- name: ListCircleLeadersByCircleIDs :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE circle_user.is_leader = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListCircleLeadersByCircleIDsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListCircleLeadersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListCircleLeadersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listCircleLeadersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCircleLeadersByCircleIDsRow
	for rows.Next() {
		var i ListCircleLeadersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLoginIDs = `-- name: ListUserLoginIDs :many
SELECT login_id
FROM user_login_ids
WHERE user_id = $1
ORDER BY login_id
`

func (q *Queries) ListUserLoginIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserLoginIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login_id string
		if err := rows.Scan(&login_id); err != nil {
			return nil, err
		}
		items = append(items, login_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissions = `-- name: ListUserPermissions :many
SELECT permission
FROM user_permissions
WHERE user_id = $1
ORDER BY permission
`

func (q *Queries) ListUserPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role
FROM user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, password, is_verified, created_at
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Password,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCircleIDs = `-- name: ListUsersByCircleIDs :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListUsersByCircleIDsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListUsersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListUsersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listUsersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByCircleIDsRow
	for rows.Next() {
		var i ListUsersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRelations = `-- name: ListUsersWithRelations :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListUsersWithRelationsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListUsersWithRelations(ctx context.Context) ([]ListUsersWithRelationsRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRelationsRow
	for rows.Next() {
		var i ListUsersWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedCircleLeadersByCircleIDs = `-- name: ListVerifiedCircleLeadersByCircleIDs :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
  AND circle_user.is_leader = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListVerifiedCircleLeadersByCircleIDsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListVerifiedCircleLeadersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListVerifiedCircleLeadersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedCircleLeadersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedCircleLeadersByCircleIDsRow
	for rows.Next() {
		var i ListVerifiedCircleLeadersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedUsersByCircleIDs = `-- name: ListVerifiedUsersByCircleIDs :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
  AND circle_user.circle_id = ANY($1::text[])
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListVerifiedUsersByCircleIDsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListVerifiedUsersByCircleIDs(ctx context.Context, dollar_1 []string) ([]ListVerifiedUsersByCircleIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedUsersByCircleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedUsersByCircleIDsRow
	for rows.Next() {
		var i ListVerifiedUsersByCircleIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedUsersWithRelations = `-- name: ListVerifiedUsersWithRelations :many
SELECT
    users.id,
    users.display_name,
    users.is_verified,
    COALESCE(
        array_agg(DISTINCT user_login_ids.login_id) FILTER (WHERE user_login_ids.login_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS login_ids,
    COALESCE(
        array_agg(DISTINCT user_roles.role) FILTER (WHERE user_roles.role IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS roles,
    COALESCE(
        array_agg(DISTINCT user_permissions.permission) FILTER (WHERE user_permissions.permission IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS permissions,
    COALESCE(
        array_agg(DISTINCT circle_user.circle_id) FILTER (WHERE circle_user.circle_id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS circle_ids
FROM users
LEFT JOIN user_login_ids ON user_login_ids.user_id = users.id
LEFT JOIN user_roles ON user_roles.user_id = users.id
LEFT JOIN user_permissions ON user_permissions.user_id = users.id
LEFT JOIN circle_user ON circle_user.user_id = users.id
WHERE users.is_verified = true
GROUP BY users.id, users.display_name, users.is_verified
ORDER BY users.id
`

type ListVerifiedUsersWithRelationsRow struct {
	ID          string
	DisplayName string
	IsVerified  bool
	LoginIds    []string
	Roles       []string
	Permissions []string
	CircleIds   []string
}

func (q *Queries) ListVerifiedUsersWithRelations(ctx context.Context) ([]ListVerifiedUsersWithRelationsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedUsersWithRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedUsersWithRelationsRow
	for rows.Next() {
		var i ListVerifiedUsersWithRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IsVerified,
			&i.LoginIds,
			&i.Roles,
			&i.Permissions,
			&i.CircleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserDisplayNameParams struct {
	ID          string
	DisplayName string
}

type UpdateUserDisplayNameRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserIsVerified = `-- name: UpdateUserIsVerified :one
UPDATE users
SET is_verified = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserIsVerifiedParams struct {
	ID         string
	IsVerified bool
}

type UpdateUserIsVerifiedRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserIsVerified(ctx context.Context, arg UpdateUserIsVerifiedParams) (UpdateUserIsVerifiedRow, error) {
	row := q.db.QueryRow(ctx, updateUserIsVerified, arg.ID, arg.IsVerified)
	var i UpdateUserIsVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2
WHERE id = $1
RETURNING id, display_name, password, is_verified, created_at
`

type UpdateUserPasswordParams struct {
	ID       string
	Password string
}

type UpdateUserPasswordRow struct {
	ID          string
	DisplayName string
	Password    string
	IsVerified  bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}
