#!/usr/bin/env bash
#MISE description="Run static checks for the whole project"

mise run generate && \
mise run frontend-check && \
mise run email-producer-check && \
mise run email-consumer-check && \
mise run backend-check
